import React from 'react';
import { AXY_APP_ROUTES, BILLING_READY, buildSubscriptionUrl } from '../config/billing.js';

const C = { navy: '#1F2B4D', slate: '#32415C', teal: '#2C8C99', text: '#3A4358', muted: '#667085', border: '#E4E8EF', pale: '#F7F9FC' };
const label = { fontFamily: "'Roboto Mono',monospace", fontSize: '10.5px', letterSpacing: '.14em', color: C.teal, textTransform: 'uppercase', fontWeight: 700 };
const primary = { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minHeight: '46px', padding: '12px 20px', borderRadius: '10px', background: C.slate, color: '#fff', border: `1.5px solid ${C.slate}`, fontSize: '14px', fontWeight: 750 };
const outline = { ...primary, background: '#fff', color: C.slate };
const row = { display: 'flex', justifyContent: 'space-between', gap: '12px', color: '#C9D2E4', fontSize: '13px' };

function Check({ children }) {
  return <div style={{ display: 'flex', alignItems: 'flex-start', gap: '9px', color: C.text, fontSize: '13.5px', lineHeight: 1.5 }}><span aria-hidden="true" style={{ color: C.teal, fontWeight: 900 }}>✓</span><span>{children}</span></div>;
}

function Quantity({ value, onDecrease, onIncrease, name }) {
  const button = { width: '38px', height: '38px', border: `1px solid ${C.border}`, borderRadius: '9px', background: '#fff', color: C.navy, cursor: 'pointer', fontSize: '19px', fontWeight: 700 };
  return <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><button type="button" onClick={onDecrease} aria-label={`Decrease ${name}`} style={button}>−</button><span style={{ minWidth: '32px', textAlign: 'center', color: C.navy, fontSize: '17px', fontWeight: 800 }}>{value}</span><button type="button" onClick={onIncrease} aria-label={`Increase ${name}`} style={button}>+</button></div>;
}

function Module({ name, price, description, enabled, onToggle }) {
  return <div className="pr-option" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '18px', padding: '18px', border: `1px solid ${C.border}`, borderRadius: '13px', background: '#fff' }}><div><div style={{ color: C.navy, fontSize: '15px', fontWeight: 800 }}>{name} <span style={{ color: C.teal }}>€{price}/month</span></div><div style={{ marginTop: '4px', color: C.muted, fontSize: '12.5px', lineHeight: 1.5 }}>{description}</div></div><button type="button" onClick={onToggle} aria-pressed={enabled} style={{ flex: 'none', minWidth: '84px', padding: '9px 14px', borderRadius: '9px', border: `1.5px solid ${enabled ? C.teal : '#D8DEE8'}`, background: enabled ? C.teal : '#fff', color: enabled ? '#fff' : C.slate, cursor: 'pointer', fontSize: '12.5px', fontWeight: 750 }}>{enabled ? 'Included ✓' : 'Add'}</button></div>;
}

function FutureButton({ href, children, light = false }) {
  const disabled = !BILLING_READY;
  return <a href={disabled ? undefined : href} aria-disabled={disabled ? 'true' : undefined} data-billing-ready={BILLING_READY ? 'true' : 'false'} onClick={disabled ? (event) => event.preventDefault() : undefined} style={{ ...(light ? outline : primary), width: '100%', cursor: disabled ? 'not-allowed' : 'pointer', opacity: disabled ? .58 : 1 }}>{children}</a>;
}

export default function Pricing({ pUsers, pUsersDec, pUsersInc, pBU, pBUDec, pBUInc, pAddUsers, pAddUserCost, pAddBU, pAddBUCost, pAnnOn, pAnnToggle, pAnnCost, pMsgOn, pMsgToggle, pMsgCost, pTotalLabel, pScrollBuild }) {
  const subscriptionUrl = buildSubscriptionUrl({ users: pUsers, businessUnits: pBU, announcements: pAnnOn, messaging: pMsgOn });
  const packs = [{ credits: 20, price: 20, unit: '€1.00' }, { credits: 50, price: 40, unit: '€0.80', popular: true }, { credits: 100, price: 70, unit: '€0.70' }];
  return <main data-screen-label="Pricing">
    <section style={{ position: 'relative', overflow: 'hidden', background: 'linear-gradient(135deg,#1F2B4D,#32415C 60%,#2C6570)', padding: '72px 24px 66px' }}>
      <div style={{ position: 'absolute', top: '-120px', right: '-70px', width: '440px', height: '340px', background: 'radial-gradient(circle,rgba(51,214,164,.15),transparent 70%)' }} />
      <div style={{ position: 'relative', maxWidth: '790px', margin: '0 auto', textAlign: 'center' }}><div style={{ ...label, color: '#7FD4DE' }}>AXY pricing</div><h1 style={{ margin: '14px 0 0', color: '#fff', fontSize: 'clamp(36px,5vw,52px)', lineHeight: 1.08, letterSpacing: '-.035em', fontWeight: 850 }}>Start free. Add only what your business needs.</h1><p style={{ maxWidth: '650px', margin: '18px auto 0', color: '#C9D2E4', fontSize: '16px', lineHeight: 1.65 }}>One clear free plan, transparent monthly additions, and optional AI image credits.</p><div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '12px', marginTop: '28px' }}><a href={AXY_APP_ROUTES.onboarding} style={{ ...primary, background: '#fff', color: C.navy, borderColor: '#fff' }}>Start free</a><button type="button" onClick={pScrollBuild} style={{ ...outline, background: 'transparent', color: '#fff', borderColor: 'rgba(255,255,255,.5)', cursor: 'pointer' }}>Calculate your plan</button><a href={AXY_APP_ROUTES.authentication} style={{ display: 'inline-flex', alignItems: 'center', padding: '12px', color: '#fff', fontSize: '14px', fontWeight: 700, textDecoration: 'underline', textUnderlineOffset: '4px' }}>Log in</a></div></div>
    </section>

    <section style={{ padding: '68px 24px', background: '#fff' }}><div style={{ maxWidth: '1080px', margin: '0 auto' }}><div className="pr-cards" style={{ display: 'grid', gridTemplateColumns: 'minmax(0,.9fr) minmax(0,1.1fr)', gap: '22px', alignItems: 'stretch' }}>
      <article style={{ display: 'flex', flexDirection: 'column', padding: '28px', border: `1.5px solid ${C.teal}`, borderRadius: '18px', background: '#EFF7F8' }}><div style={label}>AXY Free</div><div style={{ marginTop: '10px', color: C.navy, fontSize: '34px', fontWeight: 850 }}>€0</div><p style={{ margin: '8px 0 20px', color: C.muted, fontSize: '13.5px', lineHeight: 1.6 }}>A complete starting point for one business unit. No credit card required.</p><div style={{ display: 'flex', flexDirection: 'column', gap: '10px', flex: 1 }}><Check>One company workspace</Check><Check>One administrator</Check><Check>One business unit</Check><Check>Core AXY platform access</Check><Check>Five one-time trial image generations</Check></div><a href={AXY_APP_ROUTES.onboarding} style={{ ...primary, marginTop: '24px' }}>Start free</a></article>
      <article style={{ display: 'flex', flexDirection: 'column', padding: '28px', border: `1px solid ${C.border}`, borderRadius: '18px', background: C.pale }}><div style={label}>Build your plan</div><h2 style={{ margin: '11px 0 0', color: C.navy, fontSize: '27px', lineHeight: 1.2, fontWeight: 850 }}>Your monthly price, calculated clearly</h2><p style={{ margin: '10px 0 20px', color: C.muted, fontSize: '13.5px', lineHeight: 1.6 }}>The first administrator and first business unit are always included.</p><div style={{ display: 'flex', flexDirection: 'column', gap: '10px', flex: 1 }}><Check>Each additional user — €15/month</Check><Check>Each additional business unit — €49/month</Check><Check>Announcements — €20/month per organization</Check><Check>Messaging — €19/month per organization</Check><Check>20 monthly AI images with every paid additional business unit</Check></div><button type="button" onClick={pScrollBuild} style={{ ...outline, marginTop: '24px', cursor: 'pointer' }}>Open calculator</button></article>
    </div></div></section>

    <section id="axy-pricing-builder" style={{ padding: '72px 24px', background: C.pale, scrollMarginTop: '78px' }}><div style={{ maxWidth: '1080px', margin: '0 auto' }}><div style={{ maxWidth: '690px' }}><div style={label}>Monthly calculator</div><h2 style={{ margin: '12px 0 0', color: C.navy, fontSize: 'clamp(28px,4vw,38px)', lineHeight: 1.14, fontWeight: 850 }}>Configure the AXY setup you need.</h2><p style={{ margin: '13px 0 0', color: C.muted, fontSize: '14.5px', lineHeight: 1.65 }}>Choose total users and business units. AXY charges only for additions beyond the free starting setup.</p></div>
      <div className="pr-builder" style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1.22fr) minmax(320px,.78fr)', gap: '24px', marginTop: '30px', alignItems: 'start' }}><div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        <div className="pr-option" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '18px', padding: '18px', border: `1px solid ${C.border}`, borderRadius: '13px', background: '#fff' }}><div><div style={{ color: C.navy, fontSize: '15px', fontWeight: 800 }}>Total users</div><div style={{ marginTop: '4px', color: C.muted, fontSize: '12.5px' }}>First administrator included; then €15/month each.</div></div><Quantity value={pUsers} onDecrease={pUsersDec} onIncrease={pUsersInc} name="total users" /></div>
        <div className="pr-option" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '18px', padding: '18px', border: `1px solid ${C.border}`, borderRadius: '13px', background: '#fff' }}><div><div style={{ color: C.navy, fontSize: '15px', fontWeight: 800 }}>Total business units</div><div style={{ marginTop: '4px', color: C.muted, fontSize: '12.5px' }}>First business unit included; then €49/month each.</div></div><Quantity value={pBU} onDecrease={pBUDec} onIncrease={pBUInc} name="total business units" /></div>
        <Module name="Announcements" price="20" description="Create, manage and send announcements across your organization." enabled={pAnnOn} onToggle={pAnnToggle} />
        <Module name="Messaging" price="19" description="Use AXY messaging features. External delivery charges are separate." enabled={pMsgOn} onToggle={pMsgToggle} />
      </div><aside style={{ position: 'sticky', top: '84px', padding: '24px', borderRadius: '17px', background: 'linear-gradient(145deg,#1F2B4D,#32415C)', boxShadow: '0 18px 46px rgba(31,43,77,.2)' }}><div style={{ ...label, color: '#7FD4DE' }}>Plan summary</div><div style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '18px' }}><div style={row}><span>First administrator</span><strong style={{ color: '#fff' }}>Included</strong></div><div style={row}><span>First business unit</span><strong style={{ color: '#fff' }}>Included</strong></div>{pAddUsers > 0 && <div style={row}><span>Additional users ×{pAddUsers}</span><strong style={{ color: '#fff' }}>€{pAddUserCost}</strong></div>}{pAddBU > 0 && <div style={row}><span>Additional business units ×{pAddBU}</span><strong style={{ color: '#fff' }}>€{pAddBUCost}</strong></div>}{pAnnOn && <div style={row}><span>Announcements</span><strong style={{ color: '#fff' }}>€{pAnnCost}</strong></div>}{pMsgOn && <div style={row}><span>Messaging</span><strong style={{ color: '#fff' }}>€{pMsgCost}</strong></div>}</div><div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: '12px', marginTop: '20px', paddingTop: '18px', borderTop: '1px solid rgba(255,255,255,.17)' }}><span style={{ color: '#C9D2E4', fontSize: '13px' }}>Monthly total</span><strong style={{ color: '#fff', fontSize: '30px', lineHeight: 1 }}>{pTotalLabel}</strong></div><p style={{ margin: '13px 0 0', color: '#9FB2D6', fontSize: '10.8px', lineHeight: 1.55 }}>Prices shown are final. VAT treatment is confirmed during secure Stripe Checkout based on billing details and VAT ID.</p><div style={{ marginTop: '17px' }}><FutureButton href={subscriptionUrl}>Continue to secure checkout</FutureButton></div>{!BILLING_READY && <div style={{ marginTop: '9px', color: '#9FB2D6', fontSize: '10.5px', textAlign: 'center' }}>Secure checkout will activate when AXY billing is ready.</div>}</aside></div>
    </div></section>

    <section style={{ padding: '72px 24px', background: '#fff' }}><div style={{ maxWidth: '1080px', margin: '0 auto' }}><div style={{ maxWidth: '700px' }}><div style={label}>AI image credits</div><h2 style={{ margin: '12px 0 0', color: C.navy, fontSize: 'clamp(28px,4vw,38px)', lineHeight: 1.14, fontWeight: 850 }}>Professional product images, purchased when you need them.</h2><p style={{ margin: '13px 0 0', color: C.muted, fontSize: '14.5px', lineHeight: 1.65 }}>AXY Free includes five one-time trial images. Every paid additional business unit includes 20 monthly images.</p></div><div className="pr-packs" style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: '16px', marginTop: '28px' }}>{packs.map(pack => <article key={pack.credits} style={{ position: 'relative', display: 'flex', flexDirection: 'column', padding: '24px', border: `${pack.popular ? 1.5 : 1}px solid ${pack.popular ? C.teal : C.border}`, borderRadius: '16px', background: pack.popular ? '#EFF7F8' : C.pale }}>{pack.popular && <span style={{ position: 'absolute', top: '16px', right: '16px', padding: '4px 9px', borderRadius: '20px', background: C.teal, color: '#fff', fontSize: '9.5px', fontWeight: 800 }}>POPULAR</span>}<div style={{ color: C.navy, fontSize: '18px', fontWeight: 850 }}>{`${pack.credits} image credits`}</div><div style={{ marginTop: '12px', color: C.navy, fontSize: '32px', lineHeight: 1, fontWeight: 850 }}>{`€${pack.price}`}</div><div style={{ marginTop: '8px', color: C.muted, fontSize: '12.5px' }}>{pack.unit} per image credit</div><div style={{ display: 'flex', flexDirection: 'column', gap: '8px', margin: '18px 0 20px', flex: 1 }}><Check>One-time purchase</Check><Check>Valid for 12 months</Check><Check>One completed image uses one credit</Check></div><FutureButton href={AXY_APP_ROUTES.billing} light>Buy image credits</FutureButton></article>)}</div></div></section>

    <section style={{ padding: '62px 24px', background: C.pale }}><div style={{ maxWidth: '760px', margin: '0 auto' }}><div style={{ textAlign: 'center' }}><div style={label}>Billing, briefly answered</div><h2 style={{ margin: '11px 0 0', color: C.navy, fontSize: '28px', fontWeight: 850 }}>Simple rules, no hidden platform fees.</h2></div><div style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '25px' }}>
      <details style={{ padding: '16px 18px', border: `1px solid ${C.border}`, borderRadius: '12px', background: '#fff' }}><summary style={{ color: C.navy, fontSize: '14px', fontWeight: 750, cursor: 'pointer' }}>Can I use AXY for free?</summary><p style={{ margin: '10px 0 0', color: C.muted, fontSize: '13.5px', lineHeight: 1.65 }}>Yes. AXY Free includes one company workspace, one administrator, one business unit, core platform access and five one-time trial images. No credit card is required.</p></details>
      <details style={{ padding: '16px 18px', border: `1px solid ${C.border}`, borderRadius: '12px', background: '#fff' }}><summary style={{ color: C.navy, fontSize: '14px', fontWeight: 750, cursor: 'pointer' }}>Are Announcements and Messaging charged per business unit?</summary><p style={{ margin: '10px 0 0', color: C.muted, fontSize: '13.5px', lineHeight: 1.65 }}>No. Each module is charged once per organization, regardless of the number of business units.</p></details>
      <details style={{ padding: '16px 18px', border: `1px solid ${C.border}`, borderRadius: '12px', background: '#fff' }}><summary style={{ color: C.navy, fontSize: '14px', fontWeight: 750, cursor: 'pointer' }}>Are WhatsApp or Infobip delivery charges included?</summary><p style={{ margin: '10px 0 0', color: C.muted, fontSize: '13.5px', lineHeight: 1.65 }}>No. WhatsApp, Infobip and other external delivery charges are billed separately by the relevant provider.</p></details>
      <details style={{ padding: '16px 18px', border: `1px solid ${C.border}`, borderRadius: '12px', background: '#fff' }}><summary style={{ color: C.navy, fontSize: '14px', fontWeight: 750, cursor: 'pointer' }}>How does secure payment work?</summary><p style={{ margin: '10px 0 0', color: C.muted, fontSize: '13.5px', lineHeight: 1.65 }}>You sign in to AXY, confirm the configuration and continue to Stripe-hosted Checkout. AXY never stores card details.</p></details>
    </div></div></section>

    <section style={{ padding: '76px 24px', background: 'linear-gradient(135deg,#1F2B4D,#32415C 58%,#2C6570)', textAlign: 'center' }}><div style={{ maxWidth: '760px', margin: '0 auto' }}><h2 style={{ margin: 0, color: '#fff', fontSize: '31px', lineHeight: 1.15, fontWeight: 850 }}>Start free today. Expand when AXY proves its value.</h2><p style={{ margin: '14px auto 0', maxWidth: '590px', color: '#C9D2E4', fontSize: '14.5px', lineHeight: 1.65 }}>Create your free workspace or log in to manage an existing AXY organization.</p><div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '12px', marginTop: '24px' }}><a href={AXY_APP_ROUTES.onboarding} style={{ ...primary, background: '#fff', color: C.navy, borderColor: '#fff' }}>Start free</a><a href={AXY_APP_ROUTES.authentication} style={{ ...outline, background: 'transparent', color: '#fff', borderColor: 'rgba(255,255,255,.5)' }}>Log in</a></div></div></section>
  </main>;
}
