const en = {
  forRetailers: {
    hero: { title: ['Sell better.', 'Stock smarter.'], lead: 'See what your market wants.', body: 'AXY connects your sales team, customers, products, stock and management - so opportunities move forward, customers receive better service, and every location works with the same context.', guidedSetup: 'Get guided setup', createAccount: 'Create free account', salesApp: 'Explore the Sales App', imageAlt: 'AXY Sales App customer context and daily activity screens' },
    problem: { title: 'Most retail systems only start once a transaction is made', accent: 'AXY captures what happens before it as well.', body: 'Retailers usually only know what was sold. They rarely have a clear view of what customers considered, requested, liked, could not find, or expected to hear more about later.', items: ['They miss the products that are shown, but never sold.', 'They never see that customers are interested in unavailable items.', 'Follow-ups depend exclusively on an individual’s memory.', 'Demand signals never reach management or procurement.'], callout: 'See demand before it becomes an invoice.', imageAlt: 'AXY Sales App showing a customer conversation, products of interest and the salesperson’s daily activity' },
    opportunity: { eyebrow: 'Never miss anything', title: 'Never lose a sales opportunity', body: 'Organise customer visits, inquiries, offers, tasks and follow-ups so every active opportunity has a clear owner and next action.', link: 'Explore the Sales App', imageAlt: 'AXY Sales App customer profile with open opportunities and follow-ups' },
    dailyPlan: { eyebrow: 'Daily plan', title: 'Give every salesperson a clear daily plan', body: 'The Sales App brings today’s tasks, appointments, messages, tickets and opportunities into one mobile workspace.', callout: 'Open the app and know exactly what needs attention.', link: 'Explore the Sales App', imageAlt: 'AXY Sales App daily plan with tasks, appointments and messages' },
    engagement: { eyebrow: 'Customer engagement', title: 'Find the product while the customer is present', body: 'Browse the full catalogue, check stock across locations and request availability directly from connected manufacturers - without leaving the conversation.', details: ['Current-store stock', 'Other-location stock', 'Alternatives', 'Manufacturer request', 'Estimated delivery', 'Comparison'], callout: 'Give the customer an answer before they leave.', link: 'Explore product availability', imageAlt: 'AXY product catalogue showing watches, filters and product availability' },
    stock: { eyebrow: 'Stock smarter', title: 'Stock using real customer demand', body: 'Use products shown, wishlists, inquiries, availability requests and sales activity to improve transfers, ordering and reordering decisions.', details: ['Shown not sold', 'Requested unavailable', 'Product interest', 'Current stock', 'Reorder suggestion', 'Transfer opportunity'], callout: 'Use what customers wanted, not only what was sold.', link: 'See product demand intelligence', imageAlt: 'AXY Back Office reorder view displaying product demand and current stock' },
    metrics: { eyebrow: 'Real-time metrics', title: 'Understanding the business in real time', body: 'Give owners and managers a clear view of sales, visits, conversion, follow-up discipline, product demand, teams, brands and locations.', details: ['Sales & visits', 'Conversion', 'Open opportunities', 'Brand performance', 'Employee performance', 'Store comparison'], callout: 'Understand what is happening before the monthly report.', link: 'Explore the Back Office', imageAlt: 'AXY Back Office dashboard with sales, conversion and performance metrics' },
    value: { eyebrow: 'How the value connects', title: 'One store interaction creates value across the whole business.', body: 'A small action during normal work should create value for the salesperson, the customer, the sales manager, the owner and the buying team.', steps: [['Salesperson activity', 'Visit, products shown, interest'], ['Customer continuation', 'Wishlist, offer, inquiry'], ['Sales opportunity', 'Owned follow-up, next action'], ['Product demand', 'Shown, requested, wishlisted'], ['Stock decision', 'Transfer, order, reorder'], ['Management insight', 'Conversion, demand, teams']] },
    customer: { title: 'The relationship continues when the customer is ready', body: 'Customers can reopen the products they viewed, save favourites, review offers, access invoices and warranties, follow service activity and contact the store - without starting from zero.', details: ['Products viewed', 'Wishlist', 'Offers & Quotations', 'Inquiry', 'Appointment', 'Invoices', 'Warranty', 'Service status', 'Contact salesperson'], callout: 'The Customer App shows only the stores the customer has visited, selected or connected with. Unrelated retailers do not automatically gain access or appear in the profile.', link: 'Explore the customer experience', homeAlt: 'AXY Customer App home with products, appointments and services', serviceAlt: 'AXY Customer App product repair status and next actions' },
    suppliers: { title: 'Stop rebuilding supplier catalogues and chasing constant updates', body: 'Import approved manufacturer catalogues, receive product and price updates, request availability, exchange structured orders and reuse partner content - through one connected workflow.', capabilities: ['Import full or selected manufacturer catalogues', 'Receive images and product specifications', 'Review product and price updates', 'Request manufacturer availability', 'Send orders and reorders', 'Receive order confirmation', 'Reuse approved brand announcements', 'Manage warranty activations and extensions', 'Keep partner information current'], calloutStrong: 'Work more closely with partners,', callout: 'without giving them unrestricted access to your business or customers.', link: 'Explore the Back Office', imageAlt: 'AXY manufacturer catalogue on a tablet' },
    integration: { title: 'Use AXY independently, or connect the systems you already use', body: 'AXY supports smaller retailers as a connected retail platform, while larger organisations can seamlessly integrate their existing POS, ERP, CRM, inventory, e-commerce and analytics systems.', imageAlt: 'Existing inventory, POS, ERP, CRM, e-commerce and analytics systems connected through the AXY shared platform layer to the Customer App, partner network and Sales App', safeguards: ['Businesses keep control of their records', 'Partner visibility is permission-based', 'Customer-level data is not shared automatically', 'Aggregated insights without exposing raw data'], link: 'Explore the Back Office' },
    scale: { eyebrow: 'Start small. Scale across locations.', title: 'One store or many - keep the same operating logic.', options: [['Independent retailer', 'Start with the core sales, customer, catalogue and follow-up tools - without a complex implementation.'], ['Multi-location retailer', 'Connect stores, stock, customers, teams and management visibility across locations.'], ['Larger retail group', 'Integrate existing systems and use AXY as the sales, customer and partner collaboration layer.']] },
    reality: { eyebrow: 'Built from retail reality', title: 'Designed around the work that actually takes place inside real stores', body: 'AXY was developed around real premium retail workflows: customer visits, product presentations, follow-ups, stock questions, service, warranties, orders and multi-location operations.', callout: 'Created and tested inside a real multi-location luxury retail environment.', link: 'Explore the Sales App' },
    outcomes: { title: 'Sell better. Stock smarter. Stay connected.', items: ['Fewer missed opportunities', 'Faster answers during the sale', 'Less repetitive administration', 'Clearer visibility across every location'] },
    faq: { eyebrow: 'Questions retailers ask', title: 'Clear answers for retail teams.', items: [['Will my sales team actually use it?', 'AXY is designed for quick actions during normal store work. Salespeople receive customer context, tasks, product information and next-action suggestions directly inside the same mobile workspace.'], ['Can AXY work across multiple locations?', 'Yes. AXY can connect customers, teams, catalogues, stock and reporting across stores and business units, subject to each company’s setup and permissions.'], ['Do we need to replace our existing systems?', 'No. AXY can work independently or connect to existing POS, ERP, CRM, inventory and analytics systems.'], ['Can brands see our customers?', 'Customer-level information is not automatically shared with manufacturers or unrelated partners. Information exchange follows the retailer’s permissions and the agreed workflow.'], ['Can we start with only part of AXY?', 'Yes. Retailers can begin with the most relevant tools and expand users, locations, modules and integrations as their needs grow.']], pricingQuestion: 'What does it cost to start?', pricingBody: 'See the Pricing page and book guided setup - we map the right starting point for your business before anything is finalised.', pricingLink: 'See pricing' },
    final: { title: 'See how AXY would fit your retail business.', body: 'Review your sales workflow, product data, locations and current systems with our team. We will show where AXY can reduce missed opportunities and repeated work.', guidedSetup: 'Get guided setup', createAccount: 'Create free account', pricing: 'See pricing' },
  },
};

const it = {
  forRetailers: {
    hero: { title: ['Vendi meglio.', 'Gestisci lo stock con più intelligenza.'], lead: 'Scopri cosa desidera il tuo mercato.', body: 'AXY connette team di vendita, clienti, prodotti, stock e management, così le opportunità avanzano, i clienti ricevono un servizio migliore e ogni sede lavora con lo stesso contesto.', guidedSetup: 'Richiedi la configurazione guidata', createAccount: 'Crea un account gratuito', salesApp: 'Esplora la Sales App', imageAlt: 'Contesto cliente e attività giornaliere nella Sales App AXY' },
    problem: { title: 'La maggior parte dei sistemi retail entra in gioco solo dopo una transazione', accent: 'AXY acquisisce anche ciò che accade prima.', body: 'Di solito i retailer sanno soltanto cosa è stato venduto. Raramente vedono con chiarezza cosa i clienti hanno considerato, richiesto, apprezzato, non trovato o su cui aspettavano un aggiornamento.', items: ['Si perdono i prodotti presentati ma mai venduti.', 'Non emerge l’interesse per articoli non disponibili.', 'I follow-up dipendono esclusivamente dalla memoria del singolo.', 'I segnali di domanda non raggiungono management o acquisti.'], callout: 'Vedi la domanda prima che diventi una fattura.', imageAlt: 'Sales App AXY con una conversazione cliente, prodotti di interesse e attività giornaliere del venditore' },
    opportunity: { eyebrow: 'Non perdere nulla', title: 'Non perdere mai un’opportunità di vendita', body: 'Organizza visite, richieste, offerte, attività e follow-up affinché ogni opportunità attiva abbia un responsabile e una prossima azione chiari.', link: 'Esplora la Sales App', imageAlt: 'Profilo cliente nella Sales App AXY con opportunità e follow-up aperti' },
    dailyPlan: { eyebrow: 'Piano giornaliero', title: 'Dai a ogni venditore un piano giornaliero chiaro', body: 'La Sales App riunisce attività, appuntamenti, messaggi, ticket e opportunità di oggi in un unico spazio mobile.', callout: 'Apri l’app e sai subito cosa richiede attenzione.', link: 'Esplora la Sales App', imageAlt: 'Piano giornaliero nella Sales App AXY con attività, appuntamenti e messaggi' },
    engagement: { eyebrow: 'Coinvolgimento del cliente', title: 'Trova il prodotto mentre il cliente è ancora presente', body: 'Esplora l’intero catalogo, controlla lo stock tra le sedi e richiedi disponibilità ai produttori connessi senza interrompere la conversazione.', details: ['Stock del negozio', 'Stock delle altre sedi', 'Alternative', 'Richiesta al produttore', 'Consegna stimata', 'Confronto'], callout: 'Dai una risposta al cliente prima che se ne vada.', link: 'Esplora la disponibilità prodotto', imageAlt: 'Catalogo prodotti AXY con orologi, filtri e disponibilità' },
    stock: { eyebrow: 'Stock più intelligente', title: 'Gestisci lo stock usando la domanda reale dei clienti', body: 'Usa prodotti presentati, wishlist, richieste, domande di disponibilità e attività di vendita per migliorare trasferimenti, ordini e riordini.', details: ['Presentato, non venduto', 'Richiesto, non disponibile', 'Interesse prodotto', 'Stock attuale', 'Suggerimento di riordino', 'Opportunità di trasferimento'], callout: 'Usa ciò che i clienti desideravano, non solo ciò che è stato venduto.', link: 'Scopri l’intelligence sulla domanda', imageAlt: 'Vista riordino nel Back Office AXY con domanda di prodotto e stock attuale' },
    metrics: { eyebrow: 'Metriche in tempo reale', title: 'Comprendi l’attività in tempo reale', body: 'Offri a proprietari e manager una vista chiara su vendite, visite, conversione, disciplina di follow-up, domanda prodotto, team, brand e sedi.', details: ['Vendite e visite', 'Conversione', 'Opportunità aperte', 'Performance del brand', 'Performance dei dipendenti', 'Confronto tra negozi'], callout: 'Comprendi cosa accade prima del report mensile.', link: 'Esplora il Back Office', imageAlt: 'Dashboard del Back Office AXY con metriche di vendite, conversione e performance' },
    value: { eyebrow: 'Come si connette il valore', title: 'Un’interazione in negozio crea valore in tutta l’azienda.', body: 'Una piccola azione nel lavoro quotidiano dovrebbe creare valore per venditore, cliente, sales manager, proprietario e team acquisti.', steps: [['Attività del venditore', 'Visita, prodotti presentati, interesse'], ['Continuità del cliente', 'Wishlist, offerta, richiesta'], ['Opportunità di vendita', 'Follow-up assegnato, prossima azione'], ['Domanda prodotto', 'Presentato, richiesto, in wishlist'], ['Decisione di stock', 'Trasferimento, ordine, riordino'], ['Insight del management', 'Conversione, domanda, team']] },
    customer: { title: 'La relazione continua quando il cliente è pronto', body: 'I clienti possono riaprire i prodotti visualizzati, salvare preferiti, rivedere offerte, accedere a fatture e garanzie, seguire l’assistenza e contattare il negozio senza ripartire da zero.', details: ['Prodotti visualizzati', 'Wishlist', 'Offerte e preventivi', 'Richiesta', 'Appuntamento', 'Fatture', 'Garanzia', 'Stato assistenza', 'Contatta il venditore'], callout: 'La Customer App mostra solo i negozi visitati, scelti o connessi dal cliente. Retailer estranei non ottengono automaticamente accesso né compaiono nel profilo.', link: 'Esplora l’esperienza cliente', homeAlt: 'Home della Customer App AXY con prodotti, appuntamenti e servizi', serviceAlt: 'Stato della riparazione e prossime azioni nella Customer App AXY' },
    suppliers: { title: 'Smetti di ricostruire i cataloghi dei fornitori e inseguire continui aggiornamenti', body: 'Importa cataloghi autorizzati dei produttori, ricevi aggiornamenti di prodotto e prezzo, richiedi disponibilità, scambia ordini strutturati e riutilizza contenuti dei partner in un unico flusso connesso.', capabilities: ['Importa cataloghi completi o selezionati dei produttori', 'Ricevi immagini e specifiche di prodotto', 'Verifica aggiornamenti di prodotto e prezzo', 'Richiedi disponibilità al produttore', 'Invia ordini e riordini', 'Ricevi conferme d’ordine', 'Riutilizza annunci autorizzati del brand', 'Gestisci attivazioni ed estensioni di garanzia', 'Mantieni aggiornate le informazioni dei partner'], calloutStrong: 'Collabora più da vicino con i partner,', callout: 'senza offrire loro accesso illimitato all’azienda o ai clienti.', link: 'Esplora il Back Office', imageAlt: 'Catalogo del produttore AXY su tablet' },
    integration: { title: 'Usa AXY in modo indipendente oppure connetti i sistemi che già utilizzi', body: 'AXY supporta i retailer più piccoli come piattaforma connessa, mentre le organizzazioni più grandi possono integrare POS, ERP, CRM, inventario, e-commerce e analytics esistenti.', imageAlt: 'Sistemi esistenti di inventario, POS, ERP, CRM, e-commerce e analytics connessi tramite AXY a Customer App, rete partner e Sales App', safeguards: ['Le aziende mantengono il controllo dei propri record', 'La visibilità dei partner dipende dalle autorizzazioni', 'I dati a livello cliente non vengono condivisi automaticamente', 'Insight aggregati senza esporre dati grezzi'], link: 'Esplora il Back Office' },
    scale: { eyebrow: 'Inizia in piccolo. Cresci tra le sedi.', title: 'Uno o molti negozi: mantieni la stessa logica operativa.', options: [['Retailer indipendente', 'Inizia con gli strumenti essenziali per vendite, clienti, catalogo e follow-up senza un’implementazione complessa.'], ['Retailer multisede', 'Connetti negozi, stock, clienti, team e visibilità del management tra le sedi.'], ['Gruppo retail più grande', 'Integra i sistemi esistenti e usa AXY come livello per vendite, clienti e collaborazione con i partner.']] },
    reality: { eyebrow: 'Nata dalla realtà retail', title: 'Progettata intorno al lavoro che avviene davvero nei negozi', body: 'AXY è stata sviluppata sui flussi reali del retail premium: visite, presentazioni di prodotto, follow-up, domande sullo stock, assistenza, garanzie, ordini e operazioni multisede.', callout: 'Creata e testata in un vero ambiente retail di lusso multisede.', link: 'Esplora la Sales App' },
    outcomes: { title: 'Vendi meglio. Gestisci lo stock con più intelligenza. Resta connesso.', items: ['Meno opportunità perse', 'Risposte più rapide durante la vendita', 'Meno amministrazione ripetitiva', 'Maggiore visibilità in ogni sede'] },
    faq: { eyebrow: 'Le domande dei retailer', title: 'Risposte chiare per i team retail.', items: [['Il mio team di vendita la userà davvero?', 'AXY è progettata per azioni rapide nel normale lavoro in negozio. I venditori ricevono contesto cliente, attività, informazioni di prodotto e suggerimenti per le prossime azioni nello stesso spazio mobile.'], ['AXY può funzionare su più sedi?', 'Sì. AXY può connettere clienti, team, cataloghi, stock e report tra negozi e unità operative, in base alla configurazione e alle autorizzazioni aziendali.'], ['Dobbiamo sostituire i sistemi esistenti?', 'No. AXY può funzionare in modo indipendente o collegarsi a POS, ERP, CRM, inventario e sistemi di analytics esistenti.'], ['I brand possono vedere i nostri clienti?', 'Le informazioni a livello cliente non vengono condivise automaticamente con produttori o partner non correlati. Lo scambio segue le autorizzazioni del retailer e il flusso concordato.'], ['Possiamo iniziare solo con una parte di AXY?', 'Sì. I retailer possono iniziare dagli strumenti più rilevanti ed espandere utenti, sedi, moduli e integrazioni nel tempo.']], pricingQuestion: 'Quanto costa iniziare?', pricingBody: 'Consulta la pagina Prezzi e richiedi la configurazione guidata: individuiamo il punto di partenza giusto prima di finalizzare qualsiasi scelta.', pricingLink: 'Vedi i prezzi' },
    final: { title: 'Scopri come AXY si adatta alla tua attività retail.', body: 'Analizza con il nostro team il flusso di vendita, i dati di prodotto, le sedi e i sistemi attuali. Ti mostreremo dove AXY può ridurre opportunità perse e lavoro ripetuto.', guidedSetup: 'Richiedi la configurazione guidata', createAccount: 'Crea un account gratuito', pricing: 'Vedi i prezzi' },
  },
};

const de = {
  forRetailers: {
    hero: { title: ['Besser verkaufen.', 'Bestand intelligenter steuern.'], lead: 'Erkennen Sie, was Ihr Markt möchte.', body: 'AXY verbindet Verkaufsteam, Kunden, Produkte, Bestand und Management, damit Chancen vorankommen, Kunden besseren Service erhalten und jeder Standort mit demselben Kontext arbeitet.', guidedSetup: 'Geführte Einrichtung', createAccount: 'Kostenloses Konto erstellen', salesApp: 'Sales App entdecken', imageAlt: 'Kundenkontext und tägliche Aktivitäten in der AXY Sales App' },
    problem: { title: 'Die meisten Handelssysteme beginnen erst mit einer abgeschlossenen Transaktion', accent: 'AXY erfasst auch, was davor passiert.', body: 'Händler wissen meist nur, was verkauft wurde. Was Kunden erwogen, angefragt, gemocht, nicht gefunden oder später noch erwartet haben, bleibt selten sichtbar.', items: ['Präsentierte, aber nie verkaufte Produkte gehen verloren.', 'Interesse an nicht verfügbaren Artikeln bleibt unsichtbar.', 'Follow-ups hängen ausschließlich vom Gedächtnis einzelner Personen ab.', 'Nachfragesignale erreichen Management oder Einkauf nicht.'], callout: 'Nachfrage erkennen, bevor sie zur Rechnung wird.', imageAlt: 'AXY Sales App mit Kundengespräch, interessanten Produkten und täglichen Aktivitäten des Verkäufers' },
    opportunity: { eyebrow: 'Nichts verpassen', title: 'Keine Verkaufschance mehr verlieren', body: 'Organisieren Sie Kundenbesuche, Anfragen, Angebote, Aufgaben und Follow-ups, damit jede aktive Chance einen klaren Verantwortlichen und nächsten Schritt hat.', link: 'Sales App entdecken', imageAlt: 'Kundenprofil in der AXY Sales App mit offenen Chancen und Follow-ups' },
    dailyPlan: { eyebrow: 'Tagesplan', title: 'Geben Sie jedem Verkäufer einen klaren Tagesplan', body: 'Die Sales App bündelt heutige Aufgaben, Termine, Nachrichten, Tickets und Chancen in einem mobilen Arbeitsbereich.', callout: 'App öffnen und sofort wissen, was Aufmerksamkeit braucht.', link: 'Sales App entdecken', imageAlt: 'Tagesplan in der AXY Sales App mit Aufgaben, Terminen und Nachrichten' },
    engagement: { eyebrow: 'Kundenberatung', title: 'Das Produkt finden, solange der Kunde vor Ort ist', body: 'Durchsuchen Sie den vollständigen Katalog, prüfen Sie Bestände an verschiedenen Standorten und fragen Sie direkt bei verbundenen Herstellern an, ohne das Gespräch zu verlassen.', details: ['Bestand dieser Filiale', 'Bestand anderer Standorte', 'Alternativen', 'Herstelleranfrage', 'Geschätzte Lieferung', 'Vergleich'], callout: 'Geben Sie dem Kunden eine Antwort, bevor er geht.', link: 'Produktverfügbarkeit entdecken', imageAlt: 'AXY Produktkatalog mit Uhren, Filtern und Produktverfügbarkeit' },
    stock: { eyebrow: 'Bestand intelligenter steuern', title: 'Bestand anhand realer Kundennachfrage planen', body: 'Nutzen Sie präsentierte Produkte, Wunschlisten, Anfragen, Verfügbarkeitsanfragen und Verkaufsaktivität für bessere Transfers, Bestellungen und Nachbestellungen.', details: ['Präsentiert, nicht verkauft', 'Angefragt, nicht verfügbar', 'Produktinteresse', 'Aktueller Bestand', 'Nachbestellvorschlag', 'Transferchance'], callout: 'Nutzen Sie, was Kunden wollten, nicht nur, was verkauft wurde.', link: 'Analyse der Produktnachfrage', imageAlt: 'Nachbestellansicht im AXY Back Office mit Produktnachfrage und aktuellem Bestand' },
    metrics: { eyebrow: 'Echtzeitkennzahlen', title: 'Das Geschäft in Echtzeit verstehen', body: 'Geben Sie Eigentümern und Managern klare Sicht auf Verkäufe, Besuche, Conversion, Follow-up-Disziplin, Produktnachfrage, Teams, Marken und Standorte.', details: ['Verkäufe & Besuche', 'Conversion', 'Offene Chancen', 'Markenleistung', 'Mitarbeiterleistung', 'Filialvergleich'], callout: 'Verstehen, was passiert, bevor der Monatsbericht erscheint.', link: 'Back Office entdecken', imageAlt: 'AXY Back Office Dashboard mit Verkaufs-, Conversion- und Leistungskennzahlen' },
    value: { eyebrow: 'So entsteht verbundener Wert', title: 'Eine Interaktion im Geschäft schafft Wert im gesamten Unternehmen.', body: 'Eine kleine Aktion im normalen Arbeitsablauf sollte Wert für Verkäufer, Kunde, Sales Manager, Eigentümer und Einkaufsteam schaffen.', steps: [['Verkäuferaktivität', 'Besuch, präsentierte Produkte, Interesse'], ['Fortführung durch den Kunden', 'Wunschliste, Angebot, Anfrage'], ['Verkaufschance', 'Zugeordnetes Follow-up, nächste Aktion'], ['Produktnachfrage', 'Präsentiert, angefragt, gespeichert'], ['Bestandsentscheidung', 'Transfer, Bestellung, Nachbestellung'], ['Managementerkenntnis', 'Conversion, Nachfrage, Teams']] },
    customer: { title: 'Die Beziehung wird fortgeführt, wenn der Kunde bereit ist', body: 'Kunden können angesehene Produkte erneut öffnen, Favoriten speichern, Angebote prüfen, auf Rechnungen und Garantien zugreifen, Service verfolgen und das Geschäft kontaktieren, ohne neu zu beginnen.', details: ['Angesehene Produkte', 'Wunschliste', 'Angebote & Kostenvoranschläge', 'Anfrage', 'Termin', 'Rechnungen', 'Garantie', 'Servicestatus', 'Verkäufer kontaktieren'], callout: 'Die Customer App zeigt nur Geschäfte, die der Kunde besucht, ausgewählt oder verbunden hat. Andere Händler erhalten nicht automatisch Zugriff und erscheinen nicht im Profil.', link: 'Kundenerlebnis entdecken', homeAlt: 'Startseite der AXY Customer App mit Produkten, Terminen und Services', serviceAlt: 'Reparaturstatus und nächste Schritte in der AXY Customer App' },
    suppliers: { title: 'Lieferantenkataloge nicht mehr neu aufbauen und Updates hinterherlaufen', body: 'Importieren Sie freigegebene Herstellerkataloge, empfangen Sie Produkt- und Preisupdates, fragen Sie Verfügbarkeit an, tauschen Sie strukturierte Bestellungen aus und verwenden Sie Partnerinhalte in einem Workflow.', capabilities: ['Vollständige oder ausgewählte Herstellerkataloge importieren', 'Bilder und Produktspezifikationen empfangen', 'Produkt- und Preisupdates prüfen', 'Herstellerverfügbarkeit anfragen', 'Bestellungen und Nachbestellungen senden', 'Bestellbestätigung empfangen', 'Freigegebene Markenankündigungen wiederverwenden', 'Garantieaktivierungen und -verlängerungen verwalten', 'Partnerinformationen aktuell halten'], calloutStrong: 'Arbeiten Sie enger mit Partnern zusammen,', callout: 'ohne ihnen uneingeschränkten Zugriff auf Ihr Unternehmen oder Ihre Kunden zu geben.', link: 'Back Office entdecken', imageAlt: 'AXY Herstellerkatalog auf einem Tablet' },
    integration: { title: 'AXY eigenständig nutzen oder bestehende Systeme verbinden', body: 'AXY unterstützt kleinere Händler als vernetzte Plattform, während größere Organisationen POS, ERP, CRM, Bestand, E-Commerce und Analyse nahtlos integrieren können.', imageAlt: 'Bestehende Bestands-, POS-, ERP-, CRM-, E-Commerce- und Analysesysteme, die über AXY mit Customer App, Partnernetzwerk und Sales App verbunden sind', safeguards: ['Unternehmen behalten die Kontrolle über ihre Datensätze', 'Partnersichtbarkeit basiert auf Berechtigungen', 'Daten auf Kundenebene werden nicht automatisch geteilt', 'Aggregierte Erkenntnisse ohne Offenlegung von Rohdaten'], link: 'Back Office entdecken' },
    scale: { eyebrow: 'Klein starten. Standortübergreifend wachsen.', title: 'Eine Filiale oder viele – dieselbe Betriebslogik beibehalten.', options: [['Unabhängiger Händler', 'Mit den wichtigsten Tools für Verkauf, Kunden, Katalog und Follow-up starten – ohne komplexe Implementierung.'], ['Händler mit mehreren Standorten', 'Filialen, Bestand, Kunden, Teams und Managementsicht standortübergreifend verbinden.'], ['Größere Handelsgruppe', 'Bestehende Systeme integrieren und AXY als Ebene für Verkauf, Kunden und Partnerzusammenarbeit nutzen.']] },
    reality: { eyebrow: 'Aus der Handelspraxis entstanden', title: 'Entwickelt für die Arbeit, die in echten Geschäften stattfindet', body: 'AXY wurde rund um reale Premium-Handelsabläufe entwickelt: Kundenbesuche, Produktpräsentationen, Follow-ups, Bestandsfragen, Service, Garantien, Bestellungen und standortübergreifende Abläufe.', callout: 'In einer realen, standortübergreifenden Luxusumgebung entwickelt und getestet.', link: 'Sales App entdecken' },
    outcomes: { title: 'Besser verkaufen. Bestand intelligenter steuern. Verbunden bleiben.', items: ['Weniger verpasste Chancen', 'Schnellere Antworten im Verkauf', 'Weniger wiederholte Administration', 'Klarere Sicht über alle Standorte'] },
    faq: { eyebrow: 'Fragen von Händlern', title: 'Klare Antworten für Handelsteams.', items: [['Wird mein Verkaufsteam AXY wirklich nutzen?', 'AXY ist für schnelle Aktionen im normalen Filialalltag konzipiert. Verkäufer erhalten Kundenkontext, Aufgaben, Produktinformationen und Vorschläge für nächste Schritte im selben mobilen Arbeitsbereich.'], ['Funktioniert AXY über mehrere Standorte hinweg?', 'Ja. AXY kann Kunden, Teams, Kataloge, Bestand und Berichte über Filialen und Geschäftseinheiten verbinden – entsprechend Einrichtung und Berechtigungen des Unternehmens.'], ['Müssen wir bestehende Systeme ersetzen?', 'Nein. AXY kann eigenständig arbeiten oder bestehende POS-, ERP-, CRM-, Bestands- und Analysesysteme verbinden.'], ['Können Marken unsere Kunden sehen?', 'Informationen auf Kundenebene werden nicht automatisch mit Herstellern oder unbeteiligten Partnern geteilt. Der Austausch folgt den Berechtigungen des Händlers und dem vereinbarten Workflow.'], ['Können wir nur mit einem Teil von AXY starten?', 'Ja. Händler können mit den wichtigsten Tools beginnen und Nutzer, Standorte, Module und Integrationen nach Bedarf erweitern.']], pricingQuestion: 'Was kostet der Einstieg?', pricingBody: 'Sehen Sie sich die Preisseite an und buchen Sie die geführte Einrichtung. Wir bestimmen den passenden Startpunkt, bevor etwas finalisiert wird.', pricingLink: 'Preise ansehen' },
    final: { title: 'Sehen Sie, wie AXY zu Ihrem Handelsunternehmen passt.', body: 'Prüfen Sie mit unserem Team Verkaufsworkflow, Produktdaten, Standorte und aktuelle Systeme. Wir zeigen, wo AXY verpasste Chancen und wiederholte Arbeit reduziert.', guidedSetup: 'Geführte Einrichtung', createAccount: 'Kostenloses Konto erstellen', pricing: 'Preise ansehen' },
  },
};

const fr = {
  forRetailers: {
    hero: { title: ['Mieux vendre.', 'Gérer les stocks plus intelligemment.'], lead: 'Découvrez ce que veut votre marché.', body: 'AXY relie équipe de vente, clients, produits, stocks et management afin que les opportunités avancent, que les clients soient mieux servis et que chaque site partage le même contexte.', guidedSetup: 'Configuration guidée', createAccount: 'Créer un compte gratuit', salesApp: 'Découvrir la Sales App', imageAlt: 'Contexte client et activité quotidienne dans la Sales App AXY' },
    problem: { title: 'La plupart des systèmes retail ne commencent qu’une fois la transaction conclue', accent: 'AXY collecte également ce qui se passe avant.', body: 'Les détaillants savent généralement uniquement ce qui a été vendu. Ils voient rarement ce que les clients ont envisagé, demandé, apprécié, recherché sans succès ou souhaité revoir plus tard.', items: ['Les produits présentés mais jamais vendus disparaissent.', 'L’intérêt pour des articles indisponibles reste invisible.', 'Les suivis dépendent entièrement de la mémoire d’une personne.', 'Les signaux de demande n’atteignent ni le management ni les achats.'], callout: 'Voyez la demande avant qu’elle ne devienne une facture.', imageAlt: 'Sales App AXY montrant un échange client, des produits d’intérêt et l’activité quotidienne du vendeur' },
    opportunity: { eyebrow: 'Ne rien manquer', title: 'Ne perdez plus aucune opportunité de vente', body: 'Organisez visites, demandes, offres, tâches et suivis pour que chaque opportunité active ait un responsable et une prochaine action clairs.', link: 'Découvrir la Sales App', imageAlt: 'Profil client dans la Sales App AXY avec opportunités et suivis ouverts' },
    dailyPlan: { eyebrow: 'Plan quotidien', title: 'Donnez à chaque vendeur un plan quotidien clair', body: 'La Sales App réunit tâches, rendez-vous, messages, tickets et opportunités du jour dans un même espace mobile.', callout: 'Ouvrez l’app et sachez immédiatement ce qui exige votre attention.', link: 'Découvrir la Sales App', imageAlt: 'Plan quotidien dans la Sales App AXY avec tâches, rendez-vous et messages' },
    engagement: { eyebrow: 'Engagement client', title: 'Trouvez le produit pendant que le client est présent', body: 'Parcourez tout le catalogue, vérifiez les stocks entre les sites et demandez la disponibilité aux fabricants connectés sans quitter la conversation.', details: ['Stock du magasin', 'Stock des autres sites', 'Alternatives', 'Demande au fabricant', 'Livraison estimée', 'Comparaison'], callout: 'Donnez une réponse au client avant son départ.', link: 'Découvrir la disponibilité produit', imageAlt: 'Catalogue produit AXY présentant montres, filtres et disponibilité' },
    stock: { eyebrow: 'Des stocks plus intelligents', title: 'Planifiez les stocks à partir de la demande réelle', body: 'Utilisez produits présentés, listes d’envies, demandes, requêtes de disponibilité et activité commerciale pour améliorer transferts, commandes et réassorts.', details: ['Présenté, non vendu', 'Demandé, indisponible', 'Intérêt produit', 'Stock actuel', 'Suggestion de réassort', 'Opportunité de transfert'], callout: 'Utilisez ce que les clients voulaient, pas seulement ce qui a été vendu.', link: 'Voir l’analyse de la demande produit', imageAlt: 'Vue de réassort du Back Office AXY avec demande produit et stock actuel' },
    metrics: { eyebrow: 'Indicateurs en temps réel', title: 'Comprendre l’activité en temps réel', body: 'Donnez aux dirigeants et managers une vue claire des ventes, visites, conversions, suivis, demande produit, équipes, marques et sites.', details: ['Ventes & visites', 'Conversion', 'Opportunités ouvertes', 'Performance de la marque', 'Performance des collaborateurs', 'Comparaison des magasins'], callout: 'Comprenez ce qui se passe avant le rapport mensuel.', link: 'Découvrir le Back Office', imageAlt: 'Dashboard du Back Office AXY avec indicateurs de ventes, conversion et performance' },
    value: { eyebrow: 'Comment la valeur se connecte', title: 'Une interaction en magasin crée de la valeur dans toute l’entreprise.', body: 'Une petite action dans le travail quotidien doit créer de la valeur pour le vendeur, le client, le sales manager, le dirigeant et l’équipe achats.', steps: [['Activité du vendeur', 'Visite, produits présentés, intérêt'], ['Continuité client', 'Liste d’envies, offre, demande'], ['Opportunité de vente', 'Suivi attribué, prochaine action'], ['Demande produit', 'Présenté, demandé, enregistré'], ['Décision de stock', 'Transfert, commande, réassort'], ['Insight management', 'Conversion, demande, équipes']] },
    customer: { title: 'La relation continue lorsque le client est prêt', body: 'Les clients peuvent retrouver les produits consultés, enregistrer leurs favoris, revoir les offres, accéder aux factures et garanties, suivre le service et contacter le magasin sans repartir de zéro.', details: ['Produits consultés', 'Liste d’envies', 'Offres & devis', 'Demande', 'Rendez-vous', 'Factures', 'Garantie', 'État du service', 'Contacter le vendeur'], callout: 'La Customer App affiche uniquement les magasins visités, choisis ou connectés par le client. Les autres détaillants n’obtiennent pas automatiquement accès et n’apparaissent pas dans le profil.', link: 'Découvrir l’expérience client', homeAlt: 'Accueil de la Customer App AXY avec produits, rendez-vous et services', serviceAlt: 'État de réparation et prochaines actions dans la Customer App AXY' },
    suppliers: { title: 'Ne reconstruisez plus les catalogues fournisseurs et ne courez plus après les mises à jour', body: 'Importez les catalogues fabricants autorisés, recevez les mises à jour produit et prix, demandez la disponibilité, échangez des commandes structurées et réutilisez les contenus partenaires dans un workflow connecté.', capabilities: ['Importer tout ou partie des catalogues fabricants', 'Recevoir images et spécifications produit', 'Examiner les mises à jour produit et prix', 'Demander la disponibilité au fabricant', 'Envoyer commandes et réassorts', 'Recevoir les confirmations de commande', 'Réutiliser les annonces de marque autorisées', 'Gérer activations et extensions de garantie', 'Maintenir les informations partenaires à jour'], calloutStrong: 'Collaborez plus étroitement avec vos partenaires,', callout: 'sans leur donner un accès illimité à votre activité ou à vos clients.', link: 'Découvrir le Back Office', imageAlt: 'Catalogue fabricant AXY sur une tablette' },
    integration: { title: 'Utilisez AXY seule ou connectez vos systèmes existants', body: 'AXY accompagne les petits détaillants comme plateforme retail connectée, tandis que les grandes organisations peuvent intégrer leurs POS, ERP, CRM, stocks, e-commerce et outils d’analyse.', imageAlt: 'Systèmes existants de stocks, POS, ERP, CRM, e-commerce et analyse reliés par AXY à la Customer App, au réseau partenaires et à la Sales App', safeguards: ['Les entreprises gardent le contrôle de leurs données', 'La visibilité partenaire dépend des autorisations', 'Les données client ne sont pas partagées automatiquement', 'Des insights agrégés sans exposer les données brutes'], link: 'Découvrir le Back Office' },
    scale: { eyebrow: 'Commencez petit. Déployez sur plusieurs sites.', title: 'Un magasin ou plusieurs : conservez la même logique opérationnelle.', options: [['Détaillant indépendant', 'Commencez avec les outils essentiels de vente, client, catalogue et suivi, sans mise en œuvre complexe.'], ['Détaillant multisite', 'Connectez magasins, stocks, clients, équipes et visibilité du management entre les sites.'], ['Grand groupe retail', 'Intégrez les systèmes existants et utilisez AXY comme couche de vente, client et collaboration partenaires.']] },
    reality: { eyebrow: 'Conçu à partir de la réalité retail', title: 'Pensé pour le travail qui se déroule vraiment dans les magasins', body: 'AXY a été développé autour de workflows réels du retail premium : visites, présentations produit, suivis, questions de stock, service, garanties, commandes et opérations multisites.', callout: 'Créé et testé dans un véritable environnement retail de luxe multisite.', link: 'Découvrir la Sales App' },
    outcomes: { title: 'Mieux vendre. Gérer les stocks plus intelligemment. Rester connecté.', items: ['Moins d’opportunités manquées', 'Des réponses plus rapides pendant la vente', 'Moins d’administration répétitive', 'Une visibilité plus claire sur chaque site'] },
    faq: { eyebrow: 'Les questions des détaillants', title: 'Des réponses claires pour les équipes retail.', items: [['Mon équipe de vente utilisera-t-elle vraiment AXY ?', 'AXY est conçu pour des actions rapides dans le travail quotidien. Les vendeurs reçoivent contexte client, tâches, informations produit et suggestions de prochaines actions dans le même espace mobile.'], ['AXY peut-il fonctionner sur plusieurs sites ?', 'Oui. AXY peut connecter clients, équipes, catalogues, stocks et rapports entre magasins et unités opérationnelles, selon la configuration et les autorisations de chaque entreprise.'], ['Devons-nous remplacer nos systèmes existants ?', 'Non. AXY peut fonctionner de façon autonome ou se connecter aux POS, ERP, CRM, stocks et systèmes d’analyse existants.'], ['Les marques peuvent-elles voir nos clients ?', 'Les informations client ne sont pas automatiquement partagées avec les fabricants ou partenaires non concernés. Les échanges suivent les autorisations du détaillant et le workflow convenu.'], ['Pouvons-nous commencer avec seulement une partie d’AXY ?', 'Oui. Les détaillants peuvent commencer par les outils les plus pertinents puis étendre utilisateurs, sites, modules et intégrations.']], pricingQuestion: 'Combien coûte le démarrage ?', pricingBody: 'Consultez la page Tarifs et réservez une configuration guidée : nous définissons le bon point de départ avant toute décision finale.', pricingLink: 'Voir les tarifs' },
    final: { title: 'Découvrez comment AXY s’intègre à votre activité retail.', body: 'Examinez avec notre équipe votre workflow de vente, vos données produit, vos sites et vos systèmes actuels. Nous montrerons où AXY réduit les opportunités manquées et le travail répété.', guidedSetup: 'Configuration guidée', createAccount: 'Créer un compte gratuit', pricing: 'Voir les tarifs' },
  },
};

export const forRetailersCatalog = { en, it, de, fr };

export default forRetailersCatalog;
