const en = {
  salesApp: {
    hero: { eyebrow: 'AXY Sales App', title: 'Know who to contact. What to suggest. What to do next.', lead: 'AXY brings today’s priorities, approved customer context, product information and next actions into one mobile workspace — before, during and after the visit.', guidedSetup: 'Get guided setup', createAccount: 'Request beta access', retailers: 'Explore AXY for retailers', imageAlt: 'A retail salesperson presenting a product to a customer during an in-store consultation.', caption: 'The conversation stays human. AXY keeps the context ready.' },
    questions: { eyebrow: 'A clearer sales day', title: 'The Sales App answers three practical questions.', body: 'Instead of searching across notes, messages and separate product files, the salesperson can begin with the next useful decision.', items: [{ number: '01', title: 'Who needs attention?', copy: 'Tasks, requests, appointments and follow-ups come forward when action is due.' }, { number: '02', title: 'What is relevant?', copy: 'The product, visit, customer preference and approved availability stay connected.' }, { number: '03', title: 'What should happen next?', copy: 'Create a call, task, message, offer or availability request without rebuilding the story.' }] },
    capture: { eyebrow: '01 · Capture the visit', title: 'Track the visit without stepping away from the customer.', body: 'Scan or find the product, record what was shown and keep the customer’s response connected to the visit while the conversation is still happening.', items: ['Scan a product tag or search the catalogue', 'Record products shown and customer interest', 'Carry the same context into follow-up'], imageAlt: 'A salesperson scanning a product tag with the AXY Sales App during a store visit.', caption: 'Product activity can be captured during normal selling work.' },
    suggest: { eyebrow: '02 · Suggest with context', title: 'Recommend with evidence, not memory.', body: 'AXY can surface a relevant product or follow-up using the approved activity and product information already available to the salesperson.', quoteStrong: 'AXY proposes.', quote: 'The salesperson reviews the context and decides.', note: 'Suggestions do not contact customers, reserve products or send information without a person’s approval.', imageAlt: 'AXY Sales App suggestion screen showing a recommended product and its availability.', caption: 'A grounded suggestion with product and availability context.' },
    action: { eyebrow: '03 · Take the next action', title: 'A useful insight ends with one clear next step.', body: 'Turn the context into a task, call, message, product offer or availability request. The next action stays connected to the relevant products and visit.', items: ['Choose the action and responsible person', 'Set timing and the required sub-tasks', 'Follow the work through without duplicating notes'], imageAlt: 'AXY Sales App task setup showing a product offer, checklist and choice of task, message or call.', caption: 'Turn the decision into accountable work while the context is fresh.' },
    availability: { eyebrow: '04 · Check availability', title: 'Answer availability before the conversation goes cold.', body: 'Review connected stock context or send an approved inquiry, then return with a clear answer or a relevant alternative from the same product record.', callout: 'Availability reflects the locations, systems and partner permissions connected to the workflow.', imageAlt: 'AXY Sales App availability panel showing selected store locations and an inquiry action.', caption: 'Product and availability context stay together.' },
    analytics: { eyebrow: '05 · Understand the outcome', title: 'See which sales work is moving forward.', body: 'Review aggregate sales, visits, offers, invoices and follow-up activity to understand where the team is active and where opportunities may be stalling.', items: ['Compare activity across useful time periods', 'Connect outcomes with the work that preceded them', 'Support coaching and planning with clearer context'], note: 'Analytics supports review and prioritisation — not a promise of perfect forecasting.', imageAlt: 'AXY Sales App mobile analytics showing sales, visits, offers, invoices and performance trends.', caption: 'Aggregate activity helps teams understand what is changing.' },
    faq: { eyebrow: 'Questions', title: 'Sales App, briefly answered.', items: [{ question: 'Does the Sales App work on any phone?', answer: 'It runs on standard iOS and Android devices your team already carries — no special hardware.' }, { question: 'Is it only for tracking visits?', answer: 'No. It brings together the daily workspace, product catalogue, availability, customer context, follow-up and mobile analytics. Visit capture is one part of the workflow.' }, { question: 'Does Alfred act or contact customers by itself?', answer: 'No. Alfred can suggest a relevant product or next step, but the salesperson reviews the context and decides what happens. Messages and actions remain under human control.' }, { question: 'Can we begin before every system is integrated?', answer: 'Yes. AXY can begin with a selected team and workflow, then connect more catalogue, availability and operational data as the rollout expands.' }] },
    final: { eyebrow: 'Bring the next step into focus', title: 'Give the sales team clarity before, during and after every visit.', body: 'Start with one team and workflow, then expand the connected context as it creates value.', createAccount: 'Request beta access', pricing: 'See pricing', retailers: 'Explore AXY for retailers' },
  },
};

const it = {
  salesApp: {
    hero: { eyebrow: 'AXY Sales App', title: 'Sapere chi contattare. Cosa proporre. Qual è il prossimo passo.', lead: 'AXY riunisce priorità del giorno, contesto cliente approvato, informazioni prodotto e azioni successive in un unico spazio mobile, prima, durante e dopo la visita.', guidedSetup: 'Configurazione guidata', createAccount: 'Richiedi l’accesso alla beta', retailers: 'Scopri AXY per i retailer', imageAlt: 'Un addetto vendita presenta un prodotto a una cliente durante una consulenza in negozio.', caption: 'La conversazione resta umana. AXY tiene pronto il contesto.' },
    questions: { eyebrow: 'Una giornata di vendita più chiara', title: 'Sales App risponde a tre domande pratiche.', body: 'Invece di cercare tra note, messaggi e file prodotto separati, il venditore può partire dalla prossima decisione utile.', items: [{ number: '01', title: 'Chi richiede attenzione?', copy: 'Attività, richieste, appuntamenti e follow-up emergono quando è il momento di agire.' }, { number: '02', title: 'Che cosa è rilevante?', copy: 'Prodotto, visita, preferenze del cliente e disponibilità approvata restano collegati.' }, { number: '03', title: 'Qual è il prossimo passo?', copy: 'Crea una chiamata, attività, messaggio, offerta o richiesta di disponibilità senza ricostruire la storia.' }] },
    capture: { eyebrow: '01 · Registra la visita', title: 'Segui la visita senza allontanarti dal cliente.', body: 'Scansiona o trova il prodotto, registra ciò che è stato mostrato e collega la risposta del cliente alla visita mentre la conversazione è ancora in corso.', items: ['Scansiona l’etichetta o cerca nel catalogo', 'Registra prodotti mostrati e interesse del cliente', 'Porta lo stesso contesto nel follow-up'], imageAlt: 'Un venditore scansiona l’etichetta di un prodotto con AXY Sales App durante una visita.', caption: 'L’attività prodotto si registra durante il normale lavoro di vendita.' },
    suggest: { eyebrow: '02 · Suggerisci con contesto', title: 'Consiglia in base ai dati, non alla memoria.', body: 'AXY può proporre un prodotto o follow-up pertinente usando attività approvate e informazioni prodotto già disponibili al venditore.', quoteStrong: 'AXY propone.', quote: 'Il venditore verifica il contesto e decide.', note: 'I suggerimenti non contattano i clienti, prenotano prodotti o inviano informazioni senza l’approvazione di una persona.', imageAlt: 'Schermata di suggerimento in AXY Sales App con prodotto consigliato e disponibilità.', caption: 'Un suggerimento fondato sul contesto di prodotto e disponibilità.' },
    action: { eyebrow: '03 · Agisci', title: 'Un insight utile termina con un prossimo passo chiaro.', body: 'Trasforma il contesto in un’attività, chiamata, messaggio, offerta prodotto o richiesta di disponibilità. L’azione resta collegata ai prodotti e alla visita pertinenti.', items: ['Scegli l’azione e la persona responsabile', 'Imposta tempi e sotto-attività necessarie', 'Segui il lavoro senza duplicare le note'], imageAlt: 'Configurazione attività in AXY Sales App con offerta prodotto, checklist e scelta tra attività, messaggio o chiamata.', caption: 'Trasforma la decisione in lavoro assegnato mentre il contesto è ancora fresco.' },
    availability: { eyebrow: '04 · Verifica la disponibilità', title: 'Rispondi sulla disponibilità prima che la conversazione perda slancio.', body: 'Controlla lo stock connesso o invia una richiesta approvata, quindi torna dal cliente con una risposta chiara o un’alternativa pertinente dalla stessa scheda prodotto.', callout: 'La disponibilità riflette sedi, sistemi e autorizzazioni dei partner collegati al flusso.', imageAlt: 'Pannello disponibilità di AXY Sales App con sedi selezionate e azione di richiesta.', caption: 'Contesto di prodotto e disponibilità restano insieme.' },
    analytics: { eyebrow: '05 · Comprendi il risultato', title: 'Vedi quali attività di vendita stanno avanzando.', body: 'Esamina vendite, visite, offerte, fatture e follow-up aggregati per capire dove il team è attivo e dove le opportunità rischiano di fermarsi.', items: ['Confronta l’attività in periodi utili', 'Collega i risultati al lavoro che li ha preceduti', 'Supporta coaching e pianificazione con più contesto'], note: 'Gli analytics aiutano a valutare e dare priorità, non promettono previsioni perfette.', imageAlt: 'Analytics mobile di AXY Sales App con vendite, visite, offerte, fatture e trend di performance.', caption: 'L’attività aggregata aiuta i team a capire cosa sta cambiando.' },
    faq: { eyebrow: 'Domande', title: 'Sales App, in breve.', items: [{ question: 'Sales App funziona su qualsiasi telefono?', answer: 'Funziona sui normali dispositivi iOS e Android già usati dal team, senza hardware speciale.' }, { question: 'Serve solo a registrare le visite?', answer: 'No. Riunisce spazio di lavoro quotidiano, catalogo prodotti, disponibilità, contesto cliente, follow-up e analytics mobile. La registrazione della visita è solo una parte del flusso.' }, { question: 'Alfred agisce o contatta autonomamente i clienti?', answer: 'No. Alfred può suggerire un prodotto o un prossimo passo pertinente, ma il venditore verifica il contesto e decide. Messaggi e azioni restano sotto controllo umano.' }, { question: 'Possiamo iniziare prima di integrare tutti i sistemi?', answer: 'Sì. AXY può partire da un team e un flusso selezionati, quindi collegare più dati di catalogo, disponibilità e operatività con l’espansione del progetto.' }] },
    final: { eyebrow: 'Metti a fuoco il prossimo passo', title: 'Offri al team vendite chiarezza prima, durante e dopo ogni visita.', body: 'Inizia da un team e un flusso, poi amplia il contesto connesso quando genera valore.', createAccount: 'Richiedi l’accesso alla beta', pricing: 'Vedi i prezzi', retailers: 'Scopri AXY per i retailer' },
  },
};

const de = {
  salesApp: {
    hero: { eyebrow: 'AXY Sales App', title: 'Wissen, wen Sie kontaktieren. Was Sie empfehlen. Was als Nächstes zu tun ist.', lead: 'AXY bringt heutige Prioritäten, freigegebenen Kundenkontext, Produktinformationen und nächste Schritte in einem mobilen Arbeitsbereich zusammen – vor, während und nach dem Besuch.', guidedSetup: 'Geführte Einrichtung', createAccount: 'Beta-Zugang anfragen', retailers: 'AXY für Händler entdecken', imageAlt: 'Ein Verkaufsberater präsentiert einer Kundin während einer Beratung im Geschäft ein Produkt.', caption: 'Das Gespräch bleibt persönlich. AXY hält den Kontext bereit.' },
    questions: { eyebrow: 'Ein klarerer Verkaufstag', title: 'Sales App beantwortet drei praktische Fragen.', body: 'Statt Notizen, Nachrichten und getrennte Produktdateien zu durchsuchen, beginnt der Verkäufer mit der nächsten sinnvollen Entscheidung.', items: [{ number: '01', title: 'Wer braucht Aufmerksamkeit?', copy: 'Aufgaben, Anfragen, Termine und Follow-ups rücken in den Vordergrund, sobald Handlungsbedarf besteht.' }, { number: '02', title: 'Was ist relevant?', copy: 'Produkt, Besuch, Kundenpräferenz und freigegebene Verfügbarkeit bleiben verbunden.' }, { number: '03', title: 'Was sollte als Nächstes geschehen?', copy: 'Anruf, Aufgabe, Nachricht, Angebot oder Verfügbarkeitsanfrage erstellen, ohne die Vorgeschichte neu zusammenzusetzen.' }] },
    capture: { eyebrow: '01 · Besuch erfassen', title: 'Dokumentieren Sie den Besuch, ohne sich vom Kunden abzuwenden.', body: 'Scannen oder suchen Sie das Produkt, erfassen Sie die gezeigten Artikel und verbinden Sie die Reaktion des Kunden mit dem Besuch, solange das Gespräch läuft.', items: ['Produktetikett scannen oder Katalog durchsuchen', 'Gezeigte Produkte und Kundeninteresse erfassen', 'Denselben Kontext ins Follow-up übernehmen'], imageAlt: 'Ein Verkäufer scannt während eines Ladenbesuchs ein Produktetikett mit der AXY Sales App.', caption: 'Produktaktivitäten lassen sich im normalen Verkaufsgespräch erfassen.' },
    suggest: { eyebrow: '02 · Mit Kontext empfehlen', title: 'Mit Fakten empfehlen, nicht aus dem Gedächtnis.', body: 'AXY kann anhand freigegebener Aktivitäten und bereits verfügbarer Produktinformationen ein relevantes Produkt oder Follow-up vorschlagen.', quoteStrong: 'AXY schlägt vor.', quote: 'Der Verkäufer prüft den Kontext und entscheidet.', note: 'Vorschläge kontaktieren keine Kunden, reservieren keine Produkte und senden keine Informationen ohne menschliche Freigabe.', imageAlt: 'Vorschlagsansicht der AXY Sales App mit empfohlenem Produkt und Verfügbarkeit.', caption: 'Ein fundierter Vorschlag mit Produkt- und Verfügbarkeitskontext.' },
    action: { eyebrow: '03 · Nächsten Schritt ausführen', title: 'Eine hilfreiche Erkenntnis endet mit einem klaren nächsten Schritt.', body: 'Machen Sie aus dem Kontext eine Aufgabe, einen Anruf, eine Nachricht, ein Produktangebot oder eine Verfügbarkeitsanfrage. Die Aktion bleibt mit Produkt und Besuch verbunden.', items: ['Aktion und verantwortliche Person auswählen', 'Zeitpunkt und erforderliche Teilaufgaben festlegen', 'Arbeit ohne doppelte Notizen weiterverfolgen'], imageAlt: 'Aufgabeneinrichtung in der AXY Sales App mit Produktangebot, Checkliste und Auswahl von Aufgabe, Nachricht oder Anruf.', caption: 'Die Entscheidung wird zu verantwortlicher Arbeit, solange der Kontext frisch ist.' },
    availability: { eyebrow: '04 · Verfügbarkeit prüfen', title: 'Beantworten Sie die Verfügbarkeit, bevor das Gespräch abkühlt.', body: 'Prüfen Sie verbundenen Bestand oder senden Sie eine freigegebene Anfrage und antworten Sie dann mit einer klaren Auskunft oder einer relevanten Alternative aus demselben Produktdatensatz.', callout: 'Die Verfügbarkeit spiegelt die mit dem Ablauf verbundenen Standorte, Systeme und Partnerberechtigungen wider.', imageAlt: 'Verfügbarkeitsansicht der AXY Sales App mit ausgewählten Standorten und Anfrageaktion.', caption: 'Produkt- und Verfügbarkeitskontext bleiben verbunden.' },
    analytics: { eyebrow: '05 · Ergebnis verstehen', title: 'Erkennen Sie, welche Verkaufsarbeit vorankommt.', body: 'Prüfen Sie aggregierte Verkäufe, Besuche, Angebote, Rechnungen und Follow-ups, um zu verstehen, wo das Team aktiv ist und Chancen ins Stocken geraten.', items: ['Aktivitäten über sinnvolle Zeiträume vergleichen', 'Ergebnisse mit der vorausgegangenen Arbeit verbinden', 'Coaching und Planung mit besserem Kontext unterstützen'], note: 'Analytics unterstützt Prüfung und Priorisierung – es verspricht keine perfekte Prognose.', imageAlt: 'Mobile Analytics in der AXY Sales App mit Verkäufen, Besuchen, Angeboten, Rechnungen und Leistungstrends.', caption: 'Aggregierte Aktivitäten helfen Teams zu verstehen, was sich verändert.' },
    faq: { eyebrow: 'Fragen', title: 'Sales App kurz erklärt.', items: [{ question: 'Funktioniert Sales App auf jedem Smartphone?', answer: 'Sie läuft auf gängigen iOS- und Android-Geräten, die Ihr Team bereits nutzt – ohne spezielle Hardware.' }, { question: 'Dient sie nur zur Erfassung von Besuchen?', answer: 'Nein. Sie vereint täglichen Arbeitsbereich, Produktkatalog, Verfügbarkeit, Kundenkontext, Follow-up und mobile Analytics. Die Besuchserfassung ist nur ein Teil des Ablaufs.' }, { question: 'Handelt Alfred selbstständig oder kontaktiert Kunden?', answer: 'Nein. Alfred kann ein relevantes Produkt oder einen nächsten Schritt vorschlagen, doch der Verkäufer prüft den Kontext und entscheidet. Nachrichten und Aktionen bleiben unter menschlicher Kontrolle.' }, { question: 'Können wir beginnen, bevor jedes System integriert ist?', answer: 'Ja. AXY kann mit einem ausgewählten Team und Ablauf starten und im Zuge der Erweiterung weitere Katalog-, Verfügbarkeits- und Betriebsdaten anbinden.' }] },
    final: { eyebrow: 'Den nächsten Schritt fokussieren', title: 'Geben Sie dem Verkaufsteam vor, während und nach jedem Besuch Klarheit.', body: 'Beginnen Sie mit einem Team und Ablauf und erweitern Sie den verbundenen Kontext, sobald er Mehrwert schafft.', createAccount: 'Beta-Zugang anfragen', pricing: 'Preise ansehen', retailers: 'AXY für Händler entdecken' },
  },
};

const fr = {
  salesApp: {
    hero: { eyebrow: 'AXY Sales App', title: 'Savoir qui contacter. Quoi suggérer. Quelle est la prochaine action.', lead: 'AXY réunit les priorités du jour, le contexte client approuvé, les informations produit et les prochaines actions dans un seul espace mobile, avant, pendant et après la visite.', guidedSetup: 'Configuration guidée', createAccount: 'Demander l’accès à la bêta', retailers: 'Découvrir AXY pour les détaillants', imageAlt: 'Un conseiller présente un produit à une cliente pendant une consultation en boutique.', caption: 'La conversation reste humaine. AXY tient le contexte à disposition.' },
    questions: { eyebrow: 'Une journée de vente plus claire', title: 'Sales App répond à trois questions pratiques.', body: 'Au lieu de chercher dans les notes, messages et fichiers produit séparés, le conseiller peut commencer par la prochaine décision utile.', items: [{ number: '01', title: 'Qui a besoin d’attention ?', copy: 'Les tâches, demandes, rendez-vous et suivis remontent lorsqu’une action est nécessaire.' }, { number: '02', title: 'Qu’est-ce qui est pertinent ?', copy: 'Le produit, la visite, les préférences client et la disponibilité approuvée restent reliés.' }, { number: '03', title: 'Quelle est la prochaine action ?', copy: 'Créez un appel, une tâche, un message, une offre ou une demande de disponibilité sans reconstituer l’historique.' }] },
    capture: { eyebrow: '01 · Enregistrer la visite', title: 'Suivez la visite sans vous détourner du client.', body: 'Scannez ou trouvez le produit, enregistrez ce qui a été présenté et reliez la réaction du client à la visite pendant que la conversation se poursuit.', items: ['Scanner une étiquette ou rechercher dans le catalogue', 'Enregistrer les produits présentés et l’intérêt client', 'Conserver le même contexte pour le suivi'], imageAlt: 'Un conseiller scanne l’étiquette d’un produit avec AXY Sales App pendant une visite.', caption: 'L’activité produit se saisit pendant le travail de vente habituel.' },
    suggest: { eyebrow: '02 · Suggérer avec le contexte', title: 'Recommandez avec des éléments concrets, pas de mémoire.', body: 'AXY peut faire remonter un produit ou un suivi pertinent à partir de l’activité approuvée et des informations produit déjà disponibles.', quoteStrong: 'AXY propose.', quote: 'Le conseiller examine le contexte et décide.', note: 'Les suggestions ne contactent pas les clients, ne réservent pas de produits et n’envoient aucune information sans validation humaine.', imageAlt: 'Écran de suggestion AXY Sales App avec un produit recommandé et sa disponibilité.', caption: 'Une suggestion fondée sur le contexte produit et la disponibilité.' },
    action: { eyebrow: '03 · Passer à l’action suivante', title: 'Une information utile mène à une prochaine étape claire.', body: 'Transformez le contexte en tâche, appel, message, offre produit ou demande de disponibilité. L’action reste reliée aux produits et à la visite concernés.', items: ['Choisir l’action et la personne responsable', 'Définir le calendrier et les sous-tâches nécessaires', 'Suivre le travail sans dupliquer les notes'], imageAlt: 'Configuration de tâche dans AXY Sales App avec offre produit, liste de contrôle et choix entre tâche, message ou appel.', caption: 'Transformez la décision en travail attribué tant que le contexte est frais.' },
    availability: { eyebrow: '04 · Vérifier la disponibilité', title: 'Répondez sur la disponibilité avant que la conversation ne retombe.', body: 'Consultez le stock connecté ou envoyez une demande approuvée, puis revenez avec une réponse claire ou une alternative pertinente depuis la même fiche produit.', callout: 'La disponibilité reflète les sites, systèmes et autorisations partenaires connectés au flux.', imageAlt: 'Panneau de disponibilité AXY Sales App avec sites sélectionnés et action de demande.', caption: 'Le contexte produit et la disponibilité restent ensemble.' },
    analytics: { eyebrow: '05 · Comprendre le résultat', title: 'Voyez quelles activités commerciales avancent.', body: 'Examinez les ventes, visites, offres, factures et suivis agrégés pour comprendre où l’équipe agit et où les opportunités risquent de se bloquer.', items: ['Comparer l’activité sur des périodes pertinentes', 'Relier les résultats au travail qui les a précédés', 'Soutenir le coaching et la planification avec plus de contexte'], note: 'Analytics aide à examiner et prioriser, sans promettre une prévision parfaite.', imageAlt: 'Analytics mobile dans AXY Sales App avec ventes, visites, offres, factures et tendances de performance.', caption: 'L’activité agrégée aide les équipes à comprendre ce qui évolue.' },
    faq: { eyebrow: 'Questions', title: 'Sales App, en bref.', items: [{ question: 'Sales App fonctionne-t-elle sur tous les téléphones ?', answer: 'Elle fonctionne sur les appareils iOS et Android standard que votre équipe utilise déjà, sans matériel spécial.' }, { question: 'Sert-elle uniquement à suivre les visites ?', answer: 'Non. Elle réunit l’espace de travail quotidien, le catalogue produit, la disponibilité, le contexte client, le suivi et Analytics mobile. La saisie des visites n’est qu’une partie du flux.' }, { question: 'Alfred agit-il ou contacte-t-il les clients de lui-même ?', answer: 'Non. Alfred peut suggérer un produit pertinent ou une prochaine étape, mais le conseiller examine le contexte et décide. Les messages et actions restent sous contrôle humain.' }, { question: 'Peut-on commencer avant d’avoir intégré tous les systèmes ?', answer: 'Oui. AXY peut démarrer avec une équipe et un flux choisis, puis connecter davantage de données de catalogue, disponibilité et opérations à mesure du déploiement.' }] },
    final: { eyebrow: 'Clarifiez la prochaine étape', title: 'Donnez à l’équipe commerciale de la clarté avant, pendant et après chaque visite.', body: 'Commencez avec une équipe et un flux, puis enrichissez le contexte connecté à mesure qu’il apporte de la valeur.', createAccount: 'Demander l’accès à la bêta', pricing: 'Voir les tarifs', retailers: 'Découvrir AXY pour les détaillants' },
  },
};

const salesAppCatalog = { en, it, de, fr };

export default salesAppCatalog;
