const en = {
  clienteling: {
    hero: { eyebrow: 'Use case · Retail clienteling', title: 'Clienteling that survives the shift change.', body: 'High-consideration retail runs on relationships. AXY gives every salesperson the customer’s real history — and makes the follow-up actually happen.', createAccount: 'Create free account' },
    definition: { label: 'DEFINITION', lead: 'Retail clienteling is', body: 'the practice of building long-term, personal relationships with store customers — remembering preferences, following up meaningfully and continuing the conversation between visits. It matters most where purchases are considered, emotional and worth repeating: watches, jewellery and comparable categories.', crm: 'A classic CRM knows who your customers are. It rarely knows what they tried on, what they rejected, what their partner liked, or that they asked for a reference you did not have. That context lives on the store floor — which is exactly where AXY captures it.' },
    relationship: { eyebrow: 'Through the relationship', title: 'Before, during and after every visit', phases: [
      { label: 'BEFORE', title: 'Walk in prepared', body: 'History, preferences, wishlist and open follow-ups — in the salesperson’s hand before the greeting.' },
      { label: 'DURING', title: 'Capture without breaking the moment', body: 'Products shown, liked, compared, rejected — tagged in seconds inside the conversation.' },
      { label: 'AFTER', title: 'Follow up on time, every time', body: 'Owned, dated tasks with full context; the customer continues in your branded space.', link: 'The customer side' },
    ] },
    mockup: { badge: 'MOBILE SCREEN', label: 'CUSTOMER PROFILE · PREFERENCES', description: 'An illustrative profile view bringing taste notes, wishlist and visit history into one place.', customer: 'Customer', preference: 'Prefers steel · 38mm', wishlist: 'Wishlist · 2' },
    crm: { eyebrow: 'Why not a generic CRM?', title: 'Because the store floor is not a pipeline', body: 'CRMs model deals and emails. Clienteling needs visits, products, reactions and service moments — structured retail context a pipeline tool was never built to hold. Managers see follow-up discipline and relationship health, not just “last contacted”.' },
    faq: [
      ['Does this work for teams with rotating staff?', 'That is the point — the relationship belongs to the store, not one person’s memory. Any colleague can continue with full context.'],
      ['What about customer consent?', 'Consent is captured at profile creation and respected everywhere — including what appears in the customer’s own app.'],
    ],
    final: { createAccount: 'Create free account', salesApp: 'Explore the Sales App' },
  },
  salesCapture: {
    hero: { eyebrow: 'Use case · In-store sales capture', title: 'The sale is the last 5%. Capture the other 95%.', body: 'POS and ERP record what sold. AXY records what happened — who came in, what was shown, what almost sold and what should happen next.', createAccount: 'Create free account' },
    definition: { label: 'DEFINITION', lead: 'In-store sales capture is', body: 'the structured recording of meaningful store activity before and around the transaction: visits, products presented, customer reactions, unavailable-product demand, inquiries and next steps — captured live, in seconds, by the people doing the selling.' },
    comparison: { systemsLabel: 'WHAT SYSTEMS RECORD', systems: ['Transactions', 'Stock movements', 'Invoices', 'Customer master data'], axyLabel: 'WHAT AXY ADDS', axy: ['Visits and presentations', 'Liked / compared / rejected', 'Requested but unavailable', 'Inquiries and offers', 'The agreed next step'] },
    capture: { eyebrow: 'How capture works', title: 'Six moments, seconds each', steps: [
      ['01', 'Begin the visit', 'The container for everything that follows.'],
      ['02', 'Products shown', 'Every presentation logged by scan.'],
      ['03', 'Reactions', 'Liked, compared, rejected, wishlisted.'],
      ['04', 'Unavailable demand', 'Asked-for items you did not have — captured, not shrugged off.'],
      ['05', 'Outcome', 'Inquiry, offer, invoice — or an honest “not today”.'],
      ['06', 'Next step', 'A follow-up with an owner and a date.'],
    ], effortTitle: 'The effort principle', effortBody: 'If a step takes more than a few seconds or interrupts the customer, it does not ship. Data quality comes from capture that feels like part of selling — never from forced forms.' },
    unlocks: { eyebrow: 'What it unlocks', title: 'From captured activity to better decisions', body: 'Conversion by store and salesperson, product attention versus sales, demand for what you do not stock — the raw material for the demand intelligence use case.' },
    faq: [
      ['Will salespeople resist logging?', 'They resist admin. Capture here is two taps mid-conversation, and gives them back their own follow-up list and results — the incentive is built in.'],
      ['What if a visit is missed?', 'Signals degrade gracefully — partial capture still beats none. Manager views show capture consistency so coaching happens on facts.'],
    ],
    final: { createAccount: 'Create free account', demand: 'Demand intelligence' },
  },
  demandIntelligence: {
    hero: { eyebrow: 'Use case · Product demand intelligence', title: 'Demand shows up long before the receipt.', body: 'Sales reports tell you what already happened. Interest signals — shown, wishlisted, requested, rejected — tell you what is about to. AXY structures both.', createAccount: 'Create free account' },
    dashboard: { badge: 'DASHBOARD', label: 'DEMAND VIEW', description: 'An illustrative view of product interest, conversion, unavailable requests and aging stock.', heading: 'Demand · What should I buy?', firstProduct: 'Meridian Steel', firstStats: 'Shown 8 · Req 3 · Stock 0', reorder: 'REORDER', secondProduct: 'Aria Quartz', secondStats: 'Low interest', notYet: 'NOT YET' },
    definition: { label: 'DEFINITION', lead: 'Product demand intelligence is', body: 'the use of structured in-store signals — presentations, wishlists, inquiries, rejections, availability gaps and outcomes — to understand what customers actually want, per store and across the network, before that demand is visible in sales alone.', signals: ['Products shown', 'Wishlists', 'Inquiries', 'Rejections', 'Availability gaps', 'Stock context', 'Offers', 'Purchases', 'Customer App activity'] },
    decisions: { eyebrow: 'What you decide with it', title: 'From signal to decision', cards: [
      { title: 'Buying and reorder', body: 'Interest plus availability context — restock what draws attention, not just what sold last quarter.' },
      { title: 'Attention and aging', body: 'Shown-often-never-sold and never-shown-at-all — both are actionable.' },
      { title: 'Store comparison', body: 'Which locations create interest in which lines — and where follow-up converts.' },
      { title: 'Approved brand insight', body: 'Share aggregated trends with a manufacturer — only if and when you choose.', link: 'The brand side' },
    ] },
    honesty: { label: 'HONESTY NOTE', body: 'Interest is a leading indicator, not a prediction. AXY shows you structured signals and their limits — it does not promise forecasting accuracy, and signal quality depends on capture consistency.' },
    faq: [
      ['How is this different from sales analytics?', 'Sales analytics counts outcomes. This adds the numerator you have been missing: everything customers considered — so you see demand you could have served.'],
      ['What exactly can a brand partner see?', 'Only aggregated, product-level signals you explicitly approve. Never customers, visits or your margins.'],
    ],
    final: { createAccount: 'Create free account', permissions: 'Permission model' },
  },
  collaboration: {
    hero: { eyebrow: 'Use case · Retailer–brand collaboration', title: 'One shared workflow instead of fifty email threads.', body: 'Catalogues, orders, announcements, training, warranty and approved insight — running between brand and retail partners in one structured channel, with both sides in control.', guidedSetup: 'Get guided setup' },
    workflows: { eyebrow: 'Today versus with AXY', title: 'The fragmented process, repaired', body: 'Today: product data by email, orders in spreadsheets, launch decks in chat, warranty on paper, insight nowhere. With AXY: each of those becomes a shared, permission-based workflow both sides can see.', cards: [
      { title: 'Catalogue distribution', body: 'Brand structures once; partners receive current data and imagery automatically.' },
      { title: 'Orders and replenishment', body: 'One order flow with confirmations and history — no version confusion.' },
      { title: 'Announcements and training', body: 'Launches and product stories that reach the sales floor, with confirmations back.' },
      { title: 'Warranty and service', body: 'Digital activation flows to the brand; service support flows to the store.' },
      { title: 'Approved demand context', body: 'Aggregated interest — only where the retailer grants it.', link: 'How signals work' },
      { title: 'Targets and planning', body: 'Shared commercial goals between partners.', badge: 'PLANNED' },
    ] },
    control: { eyebrow: 'Control on both sides', title: 'Cooperation, not control', body: 'The retailer decides what a brand sees, and can revoke it. The brand controls its catalogue, content and pricing recommendations — never the partner’s operation.' },
    diagram: { badge: 'WORKFLOW DIAGRAM', label: 'ONE FULL CYCLE', description: 'Catalogue, order, delivery, sell-through, warranty activation and approved insight — drawn across brand and retailer lanes with a permission gate.', retailer: 'RETAILER DATA', signal: 'APPROVED SIGNAL', brand: 'BRAND VIEW' },
    faq: [
      ['Who invites whom?', 'Either side can initiate; the connection activates when both accept. Permission defaults start at zero sharing.'],
      ['Does this replace our B2B portal?', 'It can run alongside it. Many workflows — announcements, warranty, demand context — have no home in classic B2B portals at all.'],
    ],
    final: { guidedSetup: 'Get guided setup', brands: 'AXY for brands' },
  },
};

const it = {
  clienteling: {
    hero: { eyebrow: 'Caso d’uso · Clienteling retail', title: 'Un clienteling che supera il cambio turno.', body: 'Il retail ad alta considerazione vive di relazioni. AXY offre a ogni venditore la storia reale del cliente e fa sì che il follow-up avvenga davvero.', createAccount: 'Crea un account gratuito' },
    definition: { label: 'DEFINIZIONE', lead: 'Il clienteling retail è', body: 'la pratica di costruire relazioni personali e durature con i clienti del negozio: ricordare le preferenze, dare seguito in modo rilevante e continuare la conversazione tra una visita e l’altra. È essenziale quando gli acquisti sono ponderati, emotivi e destinati a ripetersi, come per orologi, gioielli e categorie simili.', crm: 'Un CRM classico sa chi sono i clienti. Raramente sa cosa hanno provato, rifiutato, cosa è piaciuto al partner o quale referenza non era disponibile. Questo contesto nasce in negozio, proprio dove AXY lo acquisisce.' },
    relationship: { eyebrow: 'Lungo tutta la relazione', title: 'Prima, durante e dopo ogni visita', phases: [
      { label: 'PRIMA', title: 'Arriva preparato', body: 'Storico, preferenze, wishlist e follow-up aperti sono già nelle mani del venditore prima del saluto.' },
      { label: 'DURANTE', title: 'Acquisisci senza interrompere il momento', body: 'Prodotti mostrati, apprezzati, confrontati o rifiutati vengono registrati in pochi secondi durante la conversazione.' },
      { label: 'DOPO', title: 'Segui il cliente sempre al momento giusto', body: 'Attività assegnate e datate con tutto il contesto; il cliente continua nel tuo spazio di marca.', link: 'Il lato cliente' },
    ] },
    mockup: { badge: 'SCHERMATA MOBILE', label: 'PROFILO CLIENTE · PREFERENZE', description: 'Una vista illustrativa del profilo che riunisce preferenze, wishlist e storico delle visite.', customer: 'Cliente', preference: 'Preferisce acciaio · 38 mm', wishlist: 'Wishlist · 2' },
    crm: { eyebrow: 'Perché non un CRM generico?', title: 'Perché il negozio non è una pipeline', body: 'I CRM modellano trattative ed e-mail. Il clienteling richiede visite, prodotti, reazioni e momenti di assistenza: un contesto retail strutturato che una pipeline non è nata per contenere. I manager vedono disciplina di follow-up e salute della relazione, non soltanto “ultimo contatto”.' },
    faq: [['Funziona con team a turnazione?', 'È proprio questo il punto: la relazione appartiene al negozio, non alla memoria di una sola persona. Qualsiasi collega può continuare con tutto il contesto.'], ['E il consenso del cliente?', 'Il consenso viene acquisito alla creazione del profilo e rispettato ovunque, anche in ciò che appare nell’app del cliente.']],
    final: { createAccount: 'Crea un account gratuito', salesApp: 'Esplora la Sales App' },
  },
  salesCapture: {
    hero: { eyebrow: 'Caso d’uso · Acquisizione dell’attività di vendita in negozio', title: 'La vendita è l’ultimo 5%. Acquisisci il restante 95%.', body: 'POS ed ERP registrano ciò che è stato venduto. AXY registra ciò che è accaduto: chi è entrato, cosa è stato mostrato, cosa stava quasi per essere venduto e quale dovrebbe essere il prossimo passo.', createAccount: 'Crea un account gratuito' },
    definition: { label: 'DEFINIZIONE', lead: 'L’acquisizione dell’attività di vendita in negozio è', body: 'la registrazione strutturata delle attività significative prima e intorno alla transazione: visite, prodotti presentati, reazioni del cliente, domanda di articoli non disponibili, richieste e prossimi passi, acquisiti dal vivo in pochi secondi da chi vende.' },
    comparison: { systemsLabel: 'COSA REGISTRANO I SISTEMI', systems: ['Transazioni', 'Movimenti di stock', 'Fatture', 'Anagrafica clienti'], axyLabel: 'COSA AGGIUNGE AXY', axy: ['Visite e presentazioni', 'Apprezzato / confrontato / rifiutato', 'Richiesto ma non disponibile', 'Richieste e offerte', 'Il prossimo passo concordato'] },
    capture: { eyebrow: 'Come funziona l’acquisizione', title: 'Sei momenti, pochi secondi ciascuno', steps: [['01', 'Inizia la visita', 'Il contenitore di tutto ciò che segue.'], ['02', 'Prodotti mostrati', 'Ogni presentazione viene registrata tramite scansione.'], ['03', 'Reazioni', 'Apprezzato, confrontato, rifiutato, aggiunto alla wishlist.'], ['04', 'Domanda non disponibile', 'Gli articoli richiesti ma assenti vengono acquisiti, non ignorati.'], ['05', 'Esito', 'Richiesta, offerta, fattura oppure un sincero “non oggi”.'], ['06', 'Prossimo passo', 'Un follow-up con responsabile e data.']], effortTitle: 'Il principio del minimo sforzo', effortBody: 'Se un passaggio richiede più di pochi secondi o interrompe il cliente, non viene introdotto. La qualità dei dati nasce da un’acquisizione che sembra parte della vendita, mai da moduli imposti.' },
    unlocks: { eyebrow: 'Cosa rende possibile', title: 'Dall’attività acquisita a decisioni migliori', body: 'Conversione per negozio e venditore, attenzione ai prodotti rispetto alle vendite, domanda per ciò che non hai a stock: la materia prima per l’intelligence sulla domanda.' },
    faq: [['I venditori rifiuteranno di registrare le attività?', 'Rifiutano l’amministrazione. Qui bastano due tocchi durante la conversazione e ottengono la propria lista di follow-up e i risultati: l’incentivo è integrato.'], ['E se una visita non viene registrata?', 'I segnali degradano in modo graduale: un’acquisizione parziale è comunque meglio di nessuna. Le viste manageriali mostrano la costanza, così il coaching si basa sui fatti.']],
    final: { createAccount: 'Crea un account gratuito', demand: 'Intelligence sulla domanda' },
  },
  demandIntelligence: {
    hero: { eyebrow: 'Caso d’uso · Intelligence sulla domanda prodotto', title: 'La domanda emerge molto prima dello scontrino.', body: 'I report di vendita raccontano ciò che è già accaduto. I segnali di interesse — mostrato, salvato, richiesto, rifiutato — mostrano ciò che sta per accadere. AXY struttura entrambi.', createAccount: 'Crea un account gratuito' },
    dashboard: { badge: 'DASHBOARD', label: 'VISTA DOMANDA', description: 'Una vista illustrativa di interesse, conversione, richieste non disponibili e anzianità dello stock.', heading: 'Domanda · Cosa dovrei acquistare?', firstProduct: 'Meridian Steel', firstStats: 'Mostrato 8 · Rich. 3 · Stock 0', reorder: 'RIORDINA', secondProduct: 'Aria Quartz', secondStats: 'Interesse basso', notYet: 'NON ANCORA' },
    definition: { label: 'DEFINIZIONE', lead: 'L’intelligence sulla domanda prodotto è', body: 'l’uso di segnali strutturati raccolti in negozio — presentazioni, wishlist, richieste, rifiuti, indisponibilità ed esiti — per capire ciò che i clienti desiderano davvero, per negozio e nell’intera rete, prima che la domanda sia visibile nelle sole vendite.', signals: ['Prodotti mostrati', 'Wishlist', 'Richieste', 'Rifiuti', 'Indisponibilità', 'Contesto stock', 'Offerte', 'Acquisti', 'Attività nella Customer App'] },
    decisions: { eyebrow: 'Cosa puoi decidere', title: 'Dal segnale alla decisione', cards: [{ title: 'Acquisti e riordino', body: 'Interesse e disponibilità insieme: riassortisci ciò che attira attenzione, non solo ciò che si vendeva lo scorso trimestre.' }, { title: 'Attenzione e anzianità', body: 'Mostrato spesso ma mai venduto e mai mostrato: entrambi richiedono un’azione.' }, { title: 'Confronto tra negozi', body: 'Quali sedi creano interesse per quali linee e dove il follow-up converte.' }, { title: 'Insight autorizzati per il brand', body: 'Condividi trend aggregati con un produttore solo quando lo scegli.', link: 'Il lato brand' }] },
    honesty: { label: 'NOTA DI TRASPARENZA', body: 'L’interesse è un indicatore anticipatore, non una previsione. AXY mostra segnali strutturati e i loro limiti: non promette accuratezza previsionale e la qualità dipende dalla costanza dell’acquisizione.' },
    faq: [['In cosa differisce dalle analisi di vendita?', 'Le analisi di vendita contano gli esiti. Qui si aggiunge il numeratore mancante: tutto ciò che i clienti hanno considerato, così vedi la domanda che avresti potuto servire.'], ['Cosa può vedere esattamente un partner di marca?', 'Solo segnali aggregati a livello prodotto che approvi esplicitamente. Mai clienti, visite o margini.']],
    final: { createAccount: 'Crea un account gratuito', permissions: 'Modello delle autorizzazioni' },
  },
  collaboration: {
    hero: { eyebrow: 'Caso d’uso · Collaborazione retailer–brand', title: 'Un solo workflow condiviso al posto di cinquanta e-mail.', body: 'Cataloghi, ordini, annunci, formazione, garanzia e insight autorizzati scorrono tra brand e partner retail in un canale strutturato, con entrambe le parti in controllo.', guidedSetup: 'Richiedi la configurazione guidata' },
    workflows: { eyebrow: 'Oggi rispetto ad AXY', title: 'Il processo frammentato, finalmente ricomposto', body: 'Oggi: dati prodotto via e-mail, ordini nei fogli di calcolo, presentazioni di lancio in chat, garanzie su carta e nessun insight. Con AXY ogni elemento diventa un workflow condiviso e basato su autorizzazioni.', cards: [{ title: 'Distribuzione dei cataloghi', body: 'Il brand struttura una volta; i partner ricevono automaticamente dati e immagini aggiornati.' }, { title: 'Ordini e riassortimento', body: 'Un unico flusso con conferme e storico, senza confusione tra versioni.' }, { title: 'Annunci e formazione', body: 'Lanci e storie di prodotto arrivano al team di vendita, con conferme di ricezione.' }, { title: 'Garanzia e assistenza', body: 'L’attivazione digitale raggiunge il brand; il supporto assistenza torna al negozio.' }, { title: 'Contesto domanda autorizzato', body: 'Interesse aggregato, solo quando il retailer lo consente.', link: 'Come funzionano i segnali' }, { title: 'Obiettivi e pianificazione', body: 'Obiettivi commerciali condivisi tra partner.', badge: 'PIANIFICATO' }] },
    control: { eyebrow: 'Controllo da entrambe le parti', title: 'Collaborazione, non controllo', body: 'Il retailer decide cosa può vedere un brand e può revocarlo. Il brand controlla catalogo, contenuti e raccomandazioni di prezzo, mai l’operatività del partner.' },
    diagram: { badge: 'DIAGRAMMA DEL WORKFLOW', label: 'UN CICLO COMPLETO', description: 'Catalogo, ordine, consegna, sell-through, attivazione della garanzia e insight autorizzati, rappresentati nelle corsie di brand e retailer con un controllo dei permessi.', retailer: 'DATI RETAILER', signal: 'SEGNALE AUTORIZZATO', brand: 'VISTA BRAND' },
    faq: [['Chi invita chi?', 'Può iniziare entrambe le parti; la connessione si attiva quando entrambe accettano. Le autorizzazioni partono da zero condivisione.'], ['Sostituisce il nostro portale B2B?', 'Può funzionare accanto ad esso. Molti workflow — annunci, garanzie, contesto domanda — non trovano spazio nei portali B2B classici.']],
    final: { guidedSetup: 'Richiedi la configurazione guidata', brands: 'AXY per i brand' },
  },
};

const de = {
  clienteling: {
    hero: { eyebrow: 'Anwendungsfall · Retail Clienteling', title: 'Clienteling, das den Schichtwechsel übersteht.', body: 'Beratungsintensiver Handel lebt von Beziehungen. AXY gibt jedem Verkäufer die echte Kundenhistorie und sorgt dafür, dass Follow-ups tatsächlich stattfinden.', createAccount: 'Kostenloses Konto erstellen' },
    definition: { label: 'DEFINITION', lead: 'Retail Clienteling ist', body: 'der Aufbau langfristiger, persönlicher Beziehungen zu Kunden im Geschäft: Präferenzen merken, sinnvoll nachfassen und das Gespräch zwischen Besuchen fortsetzen. Besonders wichtig ist dies bei wohlüberlegten, emotionalen und wiederkehrenden Käufen wie Uhren, Schmuck und vergleichbaren Kategorien.', crm: 'Ein klassisches CRM weiß, wer Ihre Kunden sind. Es weiß selten, was sie anprobiert oder abgelehnt haben, was ihrem Partner gefiel oder nach welcher nicht verfügbaren Referenz sie fragten. Dieser Kontext entsteht auf der Verkaufsfläche – genau dort erfasst ihn AXY.' },
    relationship: { eyebrow: 'Über die gesamte Beziehung', title: 'Vor, während und nach jedem Besuch', phases: [{ label: 'VORHER', title: 'Gut vorbereitet starten', body: 'Historie, Präferenzen, Wunschliste und offene Follow-ups liegen dem Verkäufer schon vor der Begrüßung vor.' }, { label: 'WÄHREND', title: 'Erfassen, ohne den Moment zu unterbrechen', body: 'Gezeigte, favorisierte, verglichene und abgelehnte Produkte werden in Sekunden im Gespräch markiert.' }, { label: 'DANACH', title: 'Immer rechtzeitig nachfassen', body: 'Zugeordnete, terminierte Aufgaben mit vollständigem Kontext; der Kunde bleibt in Ihrem gebrandeten Bereich.', link: 'Die Kundenseite' }] },
    mockup: { badge: 'MOBILE ANSICHT', label: 'KUNDENPROFIL · PRÄFERENZEN', description: 'Eine illustrative Profilansicht, die Geschmacksnotizen, Wunschliste und Besuchshistorie zusammenführt.', customer: 'Kunde', preference: 'Bevorzugt Stahl · 38 mm', wishlist: 'Wunschliste · 2' },
    crm: { eyebrow: 'Warum kein generisches CRM?', title: 'Weil die Verkaufsfläche keine Pipeline ist', body: 'CRMs modellieren Deals und E-Mails. Clienteling braucht Besuche, Produkte, Reaktionen und Servicemomente – strukturierten Handelskontext, für den Pipeline-Tools nie entwickelt wurden. Manager sehen Follow-up-Disziplin und Beziehungsqualität, nicht nur den „letzten Kontakt“.' },
    faq: [['Funktioniert das bei wechselnden Teams?', 'Genau darum geht es: Die Beziehung gehört dem Geschäft, nicht dem Gedächtnis einer Person. Jeder Kollege kann mit vollständigem Kontext weitermachen.'], ['Wie steht es um die Kundeneinwilligung?', 'Die Einwilligung wird beim Erstellen des Profils erfasst und überall berücksichtigt – auch in der App des Kunden.']],
    final: { createAccount: 'Kostenloses Konto erstellen', salesApp: 'Sales App entdecken' },
  },
  salesCapture: {
    hero: { eyebrow: 'Anwendungsfall · Erfassung von Verkaufsaktivitäten im Geschäft', title: 'Der Verkauf macht die letzten 5 % aus. Erfassen Sie die übrigen 95 %.', body: 'POS und ERP erfassen, was verkauft wurde. AXY erfasst, was passiert ist: wer kam, was wurde gezeigt, was wäre fast verkauft worden und was folgt als Nächstes.', createAccount: 'Kostenloses Konto erstellen' },
    definition: { label: 'DEFINITION', lead: 'Die Erfassung von Verkaufsaktivitäten im Geschäft ist', body: 'die strukturierte Erfassung relevanter Aktivitäten vor und rund um die Transaktion: Besuche, präsentierte Produkte, Kundenreaktionen, Nachfrage nach nicht verfügbaren Artikeln, Anfragen und nächste Schritte – live und in Sekunden durch das Verkaufsteam.' },
    comparison: { systemsLabel: 'WAS SYSTEME ERFASSEN', systems: ['Transaktionen', 'Bestandsbewegungen', 'Rechnungen', 'Kundenstammdaten'], axyLabel: 'WAS AXY ERGÄNZT', axy: ['Besuche und Präsentationen', 'Favorisiert / verglichen / abgelehnt', 'Angefragt, aber nicht verfügbar', 'Anfragen und Angebote', 'Der vereinbarte nächste Schritt'] },
    capture: { eyebrow: 'So funktioniert die Erfassung', title: 'Sechs Momente, jeweils wenige Sekunden', steps: [['01', 'Besuch beginnen', 'Der Rahmen für alles, was folgt.'], ['02', 'Gezeigte Produkte', 'Jede Präsentation wird per Scan protokolliert.'], ['03', 'Reaktionen', 'Favorisiert, verglichen, abgelehnt, gespeichert.'], ['04', 'Nicht verfügbare Nachfrage', 'Gefragte Artikel, die nicht vorrätig waren – erfasst statt abgehakt.'], ['05', 'Ergebnis', 'Anfrage, Angebot, Rechnung oder ein ehrliches „heute nicht“.'], ['06', 'Nächster Schritt', 'Ein Follow-up mit Verantwortlichem und Datum.']], effortTitle: 'Das Aufwandsprinzip', effortBody: 'Dauert ein Schritt länger als wenige Sekunden oder unterbricht er den Kunden, wird er nicht eingeführt. Datenqualität entsteht durch Erfassung als Teil des Verkaufens, nie durch erzwungene Formulare.' },
    unlocks: { eyebrow: 'Was dadurch möglich wird', title: 'Von erfasster Aktivität zu besseren Entscheidungen', body: 'Conversion nach Filiale und Verkäufer, Produktaufmerksamkeit im Verhältnis zum Verkauf sowie Nachfrage nach nicht geführten Artikeln: die Grundlage für Demand Intelligence.' },
    faq: [['Werden Verkäufer die Erfassung ablehnen?', 'Sie lehnen Administration ab. Hier genügen zwei Klicks im Gespräch; im Gegenzug erhalten sie ihre Follow-up-Liste und Ergebnisse – der Anreiz ist integriert.'], ['Was passiert bei einem nicht erfassten Besuch?', 'Signale verlieren schrittweise an Qualität; eine teilweise Erfassung ist immer noch besser als keine. Manageransichten zeigen die Konsistenz, damit Coaching auf Fakten basiert.']],
    final: { createAccount: 'Kostenloses Konto erstellen', demand: 'Demand Intelligence' },
  },
  demandIntelligence: {
    hero: { eyebrow: 'Anwendungsfall · Analyse der Produktnachfrage', title: 'Nachfrage zeigt sich lange vor dem Beleg.', body: 'Verkaufsberichte zeigen, was bereits geschehen ist. Interessenssignale – gezeigt, gespeichert, angefragt, abgelehnt – zeigen, was sich anbahnt. AXY strukturiert beides.', createAccount: 'Kostenloses Konto erstellen' },
    dashboard: { badge: 'DASHBOARD', label: 'NACHFRAGEANSICHT', description: 'Eine illustrative Ansicht von Produktinteresse, Conversion, nicht verfügbaren Anfragen und Bestandsalter.', heading: 'Nachfrage · Was sollte ich einkaufen?', firstProduct: 'Meridian Steel', firstStats: 'Gezeigt 8 · Anfr. 3 · Bestand 0', reorder: 'NACHBESTELLEN', secondProduct: 'Aria Quartz', secondStats: 'Geringes Interesse', notYet: 'NOCH NICHT' },
    definition: { label: 'DEFINITION', lead: 'Die Analyse der Produktnachfrage ist', body: 'die Nutzung strukturierter Signale aus dem Geschäft – Präsentationen, Wunschlisten, Anfragen, Ablehnungen, Verfügbarkeitslücken und Ergebnisse –, um pro Filiale und im gesamten Netzwerk zu verstehen, was Kunden wirklich wünschen, bevor diese Nachfrage allein in Verkaufszahlen sichtbar wird.', signals: ['Gezeigte Produkte', 'Wunschlisten', 'Anfragen', 'Ablehnungen', 'Verfügbarkeitslücken', 'Bestandskontext', 'Angebote', 'Käufe', 'Aktivität in der Customer App'] },
    decisions: { eyebrow: 'Was Sie damit entscheiden', title: 'Vom Signal zur Entscheidung', cards: [{ title: 'Einkauf und Nachbestellung', body: 'Interesse plus Verfügbarkeitskontext: Bestellen Sie nach, was Aufmerksamkeit erhält, nicht nur die Verkaufsschlager des letzten Quartals.' }, { title: 'Aufmerksamkeit und Alter', body: 'Oft gezeigt, nie verkauft und überhaupt nie gezeigt – beides erfordert Maßnahmen.' }, { title: 'Filialvergleich', body: 'Welche Standorte erzeugen Interesse für welche Linien und wo Follow-ups konvertieren.' }, { title: 'Freigegebene Markenerkenntnisse', body: 'Teilen Sie aggregierte Trends mit Herstellern nur dann, wenn Sie es entscheiden.', link: 'Die Markenseite' }] },
    honesty: { label: 'TRANSPARENZHINWEIS', body: 'Interesse ist ein Frühindikator, keine Prognose. AXY zeigt strukturierte Signale und ihre Grenzen; es verspricht keine Vorhersagegenauigkeit, und die Qualität hängt von konsistenter Erfassung ab.' },
    faq: [['Wie unterscheidet sich das von Verkaufsanalysen?', 'Verkaufsanalysen zählen Ergebnisse. Hier kommt der fehlende Zähler hinzu: alles, was Kunden erwogen haben. So sehen Sie Nachfrage, die Sie hätten bedienen können.'], ['Was genau kann ein Markenpartner sehen?', 'Nur aggregierte Signale auf Produktebene, die Sie ausdrücklich freigeben. Niemals Kunden, Besuche oder Margen.']],
    final: { createAccount: 'Kostenloses Konto erstellen', permissions: 'Berechtigungsmodell' },
  },
  collaboration: {
    hero: { eyebrow: 'Anwendungsfall · Händler–Marken-Zusammenarbeit', title: 'Ein gemeinsamer Workflow statt fünfzig E-Mail-Verläufen.', body: 'Kataloge, Bestellungen, Ankündigungen, Schulungen, Garantien und freigegebene Erkenntnisse laufen zwischen Marke und Handelspartnern in einem strukturierten Kanal – beide Seiten behalten die Kontrolle.', guidedSetup: 'Geführte Einrichtung' },
    workflows: { eyebrow: 'Heute im Vergleich zu AXY', title: 'Der fragmentierte Prozess, neu verbunden', body: 'Heute: Produktdaten per E-Mail, Bestellungen in Tabellen, Launch-Präsentationen im Chat, Garantie auf Papier und Erkenntnisse nirgends. Mit AXY wird jedes Element zu einem gemeinsamen, berechtigungsbasierten Workflow.', cards: [{ title: 'Katalogverteilung', body: 'Die Marke strukturiert einmal; Partner erhalten aktuelle Daten und Bilder automatisch.' }, { title: 'Bestellungen und Nachschub', body: 'Ein Bestellprozess mit Bestätigungen und Historie – ohne Versionschaos.' }, { title: 'Ankündigungen und Schulungen', body: 'Launches und Produktgeschichten erreichen die Verkaufsfläche, inklusive Rückbestätigung.' }, { title: 'Garantie und Service', body: 'Digitale Aktivierungen gehen an die Marke; Serviceunterstützung zurück an das Geschäft.' }, { title: 'Freigegebener Nachfragekontext', body: 'Aggregiertes Interesse – nur, wenn der Händler es freigibt.', link: 'So funktionieren Signale' }, { title: 'Ziele und Planung', body: 'Gemeinsame kommerzielle Ziele zwischen Partnern.', badge: 'GEPLANT' }] },
    control: { eyebrow: 'Kontrolle auf beiden Seiten', title: 'Zusammenarbeit statt Kontrolle', body: 'Der Händler entscheidet, was eine Marke sieht, und kann den Zugriff widerrufen. Die Marke kontrolliert Katalog, Inhalte und Preisempfehlungen – niemals den Betrieb des Partners.' },
    diagram: { badge: 'WORKFLOW-DIAGRAMM', label: 'EIN VOLLSTÄNDIGER ZYKLUS', description: 'Katalog, Bestellung, Lieferung, Abverkauf, Garantieaktivierung und freigegebene Erkenntnisse über Marken- und Händlerbahnen mit einer Berechtigungsprüfung.', retailer: 'HÄNDLERDATEN', signal: 'FREIGEGEBENES SIGNAL', brand: 'MARKENANSICHT' },
    faq: [['Wer lädt wen ein?', 'Beide Seiten können beginnen; die Verbindung wird aktiv, wenn beide zustimmen. Berechtigungen starten ohne Datenfreigabe.'], ['Ersetzt das unser B2B-Portal?', 'Es kann parallel dazu laufen. Viele Workflows – Ankündigungen, Garantie, Nachfragekontext – haben in klassischen B2B-Portalen keinen Platz.']],
    final: { guidedSetup: 'Geführte Einrichtung', brands: 'AXY für Marken' },
  },
};

const fr = {
  clienteling: {
    hero: { eyebrow: 'Cas d’usage · Clienteling retail', title: 'Un clienteling qui résiste au changement d’équipe.', body: 'Le retail à forte considération repose sur les relations. AXY donne à chaque vendeur l’historique réel du client et veille à ce que le suivi ait vraiment lieu.', createAccount: 'Créer un compte gratuit' },
    definition: { label: 'DÉFINITION', lead: 'Le clienteling retail est', body: 'la pratique qui consiste à bâtir des relations personnelles durables avec les clients du magasin : mémoriser les préférences, assurer un suivi pertinent et poursuivre la conversation entre les visites. Il est essentiel pour les achats réfléchis, émotionnels et récurrents, comme les montres, les bijoux et les catégories comparables.', crm: 'Un CRM classique sait qui sont vos clients. Il sait rarement ce qu’ils ont essayé ou rejeté, ce que leur partenaire a aimé ou quelle référence indisponible ils ont demandée. Ce contexte vit en magasin, précisément là où AXY le collecte.' },
    relationship: { eyebrow: 'Tout au long de la relation', title: 'Avant, pendant et après chaque visite', phases: [{ label: 'AVANT', title: 'Arriver préparé', body: 'Historique, préférences, liste d’envies et suivis ouverts sont dans la main du vendeur avant même l’accueil.' }, { label: 'PENDANT', title: 'Collecter sans interrompre le moment', body: 'Produits présentés, appréciés, comparés ou refusés sont enregistrés en quelques secondes dans la conversation.' }, { label: 'APRÈS', title: 'Toujours relancer au bon moment', body: 'Des tâches attribuées et datées avec tout le contexte ; le client poursuit dans votre espace de marque.', link: 'Le côté client' }] },
    mockup: { badge: 'ÉCRAN MOBILE', label: 'PROFIL CLIENT · PRÉFÉRENCES', description: 'Une vue illustrative du profil réunissant préférences, liste d’envies et historique des visites.', customer: 'Client', preference: 'Préfère l’acier · 38 mm', wishlist: 'Liste d’envies · 2' },
    crm: { eyebrow: 'Pourquoi pas un CRM générique ?', title: 'Parce que le magasin n’est pas un pipeline', body: 'Les CRM modélisent opportunités et e-mails. Le clienteling exige visites, produits, réactions et moments de service : un contexte retail structuré qu’un outil de pipeline n’a jamais été conçu pour contenir. Les managers voient la discipline de suivi et la santé de la relation, pas seulement le « dernier contact ».' },
    faq: [['Cela fonctionne-t-il avec des équipes tournantes ?', 'C’est précisément l’objectif : la relation appartient au magasin, pas à la mémoire d’une personne. Tout collègue peut poursuivre avec le contexte complet.'], ['Qu’en est-il du consentement client ?', 'Le consentement est recueilli à la création du profil et respecté partout, y compris dans l’app du client.']],
    final: { createAccount: 'Créer un compte gratuit', salesApp: 'Découvrir la Sales App' },
  },
  salesCapture: {
    hero: { eyebrow: 'Cas d’usage · Saisie de l’activité commerciale en magasin', title: 'La vente représente les derniers 5 %. Saisissez les 95 % restants.', body: 'Le POS et l’ERP enregistrent ce qui a été vendu. AXY enregistre ce qui s’est passé : qui est venu, ce qui a été présenté, ce qui a failli être vendu et la prochaine action.', createAccount: 'Créer un compte gratuit' },
    definition: { label: 'DÉFINITION', lead: 'La saisie de l’activité commerciale en magasin est', body: 'l’enregistrement structuré des activités pertinentes avant et autour de la transaction : visites, produits présentés, réactions client, demande d’articles indisponibles, demandes et prochaines étapes, saisis en direct et en quelques secondes par les vendeurs.' },
    comparison: { systemsLabel: 'CE QUE LES SYSTÈMES ENREGISTRENT', systems: ['Transactions', 'Mouvements de stock', 'Factures', 'Données de référence client'], axyLabel: 'CE QU’AXY AJOUTE', axy: ['Visites et présentations', 'Apprécié / comparé / refusé', 'Demandé mais indisponible', 'Demandes et offres', 'La prochaine étape convenue'] },
    capture: { eyebrow: 'Comment fonctionne la collecte', title: 'Six moments, quelques secondes chacun', steps: [['01', 'Commencer la visite', 'Le cadre de tout ce qui suit.'], ['02', 'Produits présentés', 'Chaque présentation est enregistrée par scan.'], ['03', 'Réactions', 'Apprécié, comparé, refusé, ajouté aux envies.'], ['04', 'Demande indisponible', 'Les articles demandés mais absents sont collectés, pas ignorés.'], ['05', 'Résultat', 'Demande, offre, facture ou un honnête « pas aujourd’hui ».'], ['06', 'Prochaine étape', 'Un suivi avec un responsable et une date.']], effortTitle: 'Le principe de l’effort minimal', effortBody: 'Si une étape prend plus de quelques secondes ou interrompt le client, elle n’est pas retenue. La qualité des données vient d’une collecte intégrée à la vente, jamais de formulaires imposés.' },
    unlocks: { eyebrow: 'Ce que cela rend possible', title: 'De l’activité collectée à de meilleures décisions', body: 'Conversion par magasin et vendeur, attention produit face aux ventes, demande pour ce que vous ne stockez pas : la matière première de l’intelligence de la demande.' },
    faq: [['Les vendeurs refuseront-ils de saisir les activités ?', 'Ils refusent l’administratif. Ici, deux gestes suffisent pendant la conversation et ils récupèrent leur liste de suivis et leurs résultats : l’incitation est intégrée.'], ['Et si une visite n’est pas saisie ?', 'Les signaux se dégradent progressivement ; une collecte partielle reste préférable à aucune. Les vues managers montrent la régularité pour un coaching fondé sur les faits.']],
    final: { createAccount: 'Créer un compte gratuit', demand: 'Intelligence de la demande' },
  },
  demandIntelligence: {
    hero: { eyebrow: 'Cas d’usage · Analyse de la demande produit', title: 'La demande apparaît bien avant le ticket de caisse.', body: 'Les rapports de vente racontent ce qui s’est déjà produit. Les signaux d’intérêt — présenté, enregistré, demandé, refusé — montrent ce qui se prépare. AXY structure les deux.', createAccount: 'Créer un compte gratuit' },
    dashboard: { badge: 'DASHBOARD', label: 'VUE DE LA DEMANDE', description: 'Une vue illustrative de l’intérêt produit, de la conversion, des demandes indisponibles et de l’ancienneté du stock.', heading: 'Demande · Que devrais-je acheter ?', firstProduct: 'Meridian Steel', firstStats: 'Présenté 8 · Dem. 3 · Stock 0', reorder: 'RÉASSORTIR', secondProduct: 'Aria Quartz', secondStats: 'Faible intérêt', notYet: 'PAS ENCORE' },
    definition: { label: 'DÉFINITION', lead: 'L’analyse de la demande produit est', body: 'l’utilisation de signaux structurés recueillis en magasin — présentations, listes d’envies, demandes, refus, indisponibilités et résultats — pour comprendre ce que les clients veulent réellement, par magasin et sur tout le réseau, avant que cette demande ne soit visible dans les seules ventes.', signals: ['Produits présentés', 'Listes d’envies', 'Demandes', 'Refus', 'Indisponibilités', 'Contexte de stock', 'Offres', 'Achats', 'Activité dans la Customer App'] },
    decisions: { eyebrow: 'Ce que vous pouvez décider', title: 'Du signal à la décision', cards: [{ title: 'Achats et réassort', body: 'Intérêt et disponibilité réunis : réassortissez ce qui attire l’attention, pas seulement ce qui s’est vendu le trimestre dernier.' }, { title: 'Attention et ancienneté', body: 'Souvent présenté mais jamais vendu, ou jamais présenté : les deux exigent une action.' }, { title: 'Comparaison des magasins', body: 'Quels sites suscitent l’intérêt pour quelles lignes et où les suivis convertissent.' }, { title: 'Insight de marque autorisé', body: 'Partagez des tendances agrégées avec un fabricant uniquement lorsque vous le choisissez.', link: 'Le côté marque' }] },
    honesty: { label: 'NOTE DE TRANSPARENCE', body: 'L’intérêt est un indicateur avancé, pas une prévision. AXY montre des signaux structurés et leurs limites : il ne promet pas une précision prédictive, et la qualité dépend de la régularité de la collecte.' },
    faq: [['En quoi cela diffère-t-il de l’analyse des ventes ?', 'L’analyse des ventes compte les résultats. Ici s’ajoute le numérateur manquant : tout ce que les clients ont envisagé, pour voir la demande que vous auriez pu servir.'], ['Que peut voir exactement un partenaire de marque ?', 'Uniquement les signaux agrégés au niveau produit que vous approuvez explicitement. Jamais les clients, les visites ou vos marges.']],
    final: { createAccount: 'Créer un compte gratuit', permissions: 'Modèle d’autorisations' },
  },
  collaboration: {
    hero: { eyebrow: 'Cas d’usage · Collaboration détaillant–marque', title: 'Un workflow partagé au lieu de cinquante fils d’e-mails.', body: 'Catalogues, commandes, annonces, formation, garantie et insights autorisés circulent entre la marque et ses partenaires retail dans un canal structuré, chaque partie gardant le contrôle.', guidedSetup: 'Configuration guidée' },
    workflows: { eyebrow: 'Aujourd’hui face à AXY', title: 'Le processus fragmenté, enfin réparé', body: 'Aujourd’hui : données produit par e-mail, commandes dans des tableurs, présentations de lancement dans le chat, garanties sur papier et aucun insight. Avec AXY, chaque élément devient un workflow partagé et fondé sur les autorisations.', cards: [{ title: 'Distribution des catalogues', body: 'La marque structure une fois ; les partenaires reçoivent automatiquement données et images à jour.' }, { title: 'Commandes et réassort', body: 'Un seul flux avec confirmations et historique, sans confusion de versions.' }, { title: 'Annonces et formation', body: 'Les lancements et histoires produit atteignent le terrain de vente, avec confirmation en retour.' }, { title: 'Garantie et service', body: 'L’activation numérique va vers la marque ; le support de service revient au magasin.' }, { title: 'Contexte de demande autorisé', body: 'Intérêt agrégé, uniquement lorsque le détaillant l’autorise.', link: 'Comment fonctionnent les signaux' }, { title: 'Objectifs et planification', body: 'Des objectifs commerciaux partagés entre partenaires.', badge: 'PRÉVU' }] },
    control: { eyebrow: 'Le contrôle des deux côtés', title: 'Coopération, pas contrôle', body: 'Le détaillant décide ce qu’une marque peut voir et peut le révoquer. La marque contrôle son catalogue, ses contenus et ses recommandations de prix, jamais l’activité du partenaire.' },
    diagram: { badge: 'DIAGRAMME DU WORKFLOW', label: 'UN CYCLE COMPLET', description: 'Catalogue, commande, livraison, sell-through, activation de garantie et insight autorisé, représentés entre les couloirs marque et détaillant avec une validation des permissions.', retailer: 'DONNÉES DÉTAILLANT', signal: 'SIGNAL AUTORISÉ', brand: 'VUE MARQUE' },
    faq: [['Qui invite qui ?', 'Chaque partie peut initier ; la connexion s’active lorsque les deux acceptent. Les autorisations commencent sans aucun partage.'], ['Cela remplace-t-il notre portail B2B ?', 'Il peut fonctionner à ses côtés. De nombreux workflows — annonces, garantie, contexte de demande — n’ont aucune place dans les portails B2B classiques.']],
    final: { guidedSetup: 'Configuration guidée', brands: 'AXY pour les marques' },
  },
};

export const useCasesCatalog = { en, it, de, fr };

export default useCasesCatalog;
