export default `<p>The categories and identity of service providers used by AXY may change from time to time as the Application and its functionalities develop. AXY requires processors acting on its behalf to process personal data only in accordance with AXY’s documented instructions and applicable data protection requirements, including appropriate obligations regarding confidentiality, security and the engagement of sub-processors. AXY also requires all service providers, processors, sub-processors and other third parties that process or otherwise have access to personal data on AXY’s behalf to implement appropriate technical and organisational measures and to ensure a level of protection of personal data equivalent to, or otherwise consistent with, the level of protection required from AXY under applicable data protection laws. Such parties may process personal data only for the purposes for which the data have been disclosed to them and in accordance with applicable contractual and legal requirements.</p>
<p>Certain third-party recipients, such as:</p>
<ul class="legal-list">
<li>providers of integrated external systems, such as ERP, POS, CRM, e-commerce, loyalty, inventory or communications systems, where an integration is enabled and data exchange is necessary for the agreed functionality;</li>
<li>professional advisers, auditors, insurers, courts, regulators and competent public authorities where required by law or necessary for the establishment, exercise or defence of legal claims may act as independent controllers in respect of particular processing activities rather than as processors acting exclusively on AXY’s instructions. Where this is the case, their processing is governed by their own applicable privacy information and legal obligations.</li>
</ul>
<p>If personal data is transferred outside the European Economic Area (EEA), AXY will ensure that the transfer complies with Chapter V GDPR, including, where applicable, reliance on an adequacy decision, the European Commission’s Standard Contractual Clauses and supplementary technical or organisational measures. Information about the applicable transfer safeguard may be requested using the privacy contact details below.</p>
<h3 id="cookies-and-similar-technologies">Cookies and Similar Technologies</h3>
<p>We may use cookies and similar technologies (such as pixels, tags or similar tools) in connection with our services in order to ensure their proper and secure functioning, remember user preferences, understand how our website and services are used, improve their performance and user experience, and, where applicable, support analytics and marketing activities.</p>
<p>Cookies are small text files or similar technologies that may be stored on or accessed from your device when you use our services. Depending on their purpose, cookies may be strictly necessary for the operation and security of the services, or may be used for functional, analytics or marketing purposes.</p>
<p>Where required by applicable law, cookies and similar technologies that are not strictly necessary will only be used on the basis of your prior consent. You may give, refuse or withdraw your consent at any time through the cookie settings or other consent management mechanism made available. Withdrawal of consent does not affect the lawfulness of processing carried out before its withdrawal.</p>
<p>Certain cookies or similar technologies may be provided by third-party service providers whose technologies are integrated into our services. Such third parties may process information collected through these technologies in accordance with their respective privacy policies and, where applicable, our agreements with them.</p>
<p>You may also be able to control or delete cookies through your browser settings. Please note that disabling certain cookies, in particular strictly necessary cookies, may affect the availability or proper functioning of certain features of our services.</p>
<p>Further information regarding the specific cookies and similar technologies used, their purposes, duration and relevant third parties may, where applicable, be provided through our cookie banner, cookie settings or a separate Cookie Policy.</p>
<h3 id="privacy-storage-period">Storage period</h3>
<p>AXY retains personal data only for as long as necessary for the purpose for which it was collected, taking into account the relevant Application, the User category, the enabled functionality or module, the duration of the relevant account or business relationship, applicable statutory retention requirements and the need to establish, exercise or defend legal claims.</p>
<p>As a general rule, the following retention criteria apply:</p>
<ul class="legal-list">
<li>account, profile and access data relating to Employees / Authorized Users are retained while the relevant user remains authorized under the Customer’s account. Where employment or authorization changes, the Customer is responsible for updating, suspending or removing access. Following deactivation, personal data is deleted or anonymised when it is no longer required for account administration, security, audit, compliance or legal claims;</li>
<li>the AXY account and all related personal data under AXY’s control are retained while the Customer App account is active. Where a Customer App User selects “Delete account” through the available in-app account-deletion functionality, the User will be required to verify their identity using their password or a one-time password (OTP) and submit a request for permanent deletion of the entire AXY account and all related personal data under AXY’s control. AXY will then manually process the deletion request within one business day and, upon completion, send a confirmation to the User by e-mail. As an exception, AXY may retain personal data where and for as long as retention is required or permitted for invoicing, accounting or other statutory obligations, warranty or contractual relationships, or for the establishment, exercise or defence of legal claims;</li>
<li>wishlist, product-view, click, visit, shopping-journey, customer-follow-up and similar interaction data are retained for as long as they remain relevant to the active customer relationship and the functionality for which they were collected. Such data will be deleted or anonymised when the relevant account or relationship ends or when it is no longer necessary for those purposes, subject to any applicable legal retention requirement;</li>
<li>messages, photographs, attachments, notes and other user-provided or communication content are retained for as long as necessary to provide the relevant messaging, customer, service or business workflow and, where applicable, for a limited period thereafter where necessary for security, dispute resolution or legal claims. Where messaging is provided through an external communications provider, that provider may apply its own retention periods in accordance with its applicable terms and privacy information;</li>
<li>warranty and service data are retained for the duration of the relevant warranty or service relationship and thereafter for the period necessary to handle claims, demonstrate performance of the relevant service or comply with applicable legal obligations. Where data is shared with a manufacturer or warranty provider for a warranty extension, that recipient may retain the data in accordance with its own legal obligations and applicable privacy information;</li>
<li>technical, security, audit and system-log data are retained for a period appropriate to the relevant security, troubleshooting, fraud-prevention, audit or system-integrity purpose and are deleted or anonymised once they are no longer necessary for that purpose, unless a longer period is required in connection with a security incident or legal claim;</li>
<li>analytics, benchmarking and product-development data are retained only for as long as necessary for the relevant analysis, measurement, improvement or development purpose. Wherever reasonably possible, AXY will use aggregated, pseudonymised or anonymised data for these purposes. Data that has been irreversibly anonymised so that it no longer relates to an identified or identifiable individual is no longer personal data and may be retained for statistical, benchmarking or product-development purposes;</li>
<li>personal data processed solely on the basis of consent will no longer be processed for the consent-based purpose after consent is withdrawn, unless another legal basis permits or requires continued retention;</li>
<li>accounting, tax, employment and other records subject to statutory retention requirements are retained for the periods prescribed by applicable law.</li>
</ul>
`;
