export default `<h3 id="terms-definitions-and-general-terms">Definitions and General Terms</h3>
<p>These Terms and Conditions (“Terms”) constitute a legally binding agreement <strong>between XY Sales d.o.o., Zagreb, Jordanovac 60, OIB: 31868998641</strong> (“XY,” “AXY,” “Company,” “we,” “us,” or “our”), as the owner and operator of the AXY platform and its applications, including the AXY Back Office, AXY Sales App and AXY Customer App (together, the “Application” or “AXY”), and any person or entity that accesses, registers for or uses the Application (“User,” “you,” or “your”), as further specified below.</p>
<ul class="legal-list">
<li>an individual end customer using the AXY Customer App (“Customer App User”);</li>
<li>a business or organisation that administers an organisation account and uses AXY for its business activities (“AXY Business Customer” or “participating business”), including through its Employees / Authorized Users; or</li>
<li>a manufacturer, warranty provider or other business partner participating in functionalities made available through AXY, as applicable.</li>
</ul>
<p>The expressions used in these Terms shall have the following meaning:</p>
<p class="legal-definition">1.1 “User” means, as applicable, an Employee / Authorized User or a Customer App User and, where the context so requires, an AXY Business Customer or another person or entity that accesses, registers for or uses the Application.</p>
<p class="legal-definition">1.2 “Consumer” means a Customer App User or other User who is a natural person acting for purposes outside his or her trade, business, craft or profession.</p>
<p class="legal-definition">1.3 “AXY Business Customer” means a business or organisation that administers an organisation Account and uses the business-facing AXY functionalities.</p>
<p class="legal-definition">1.4 “Employee” or “Authorized User” means a named internal user authorized by an AXY Business Customer to access and use the AXY Sales App or other business-facing AXY functionalities.</p>
<p class="legal-definition">1.5 “Customer App User” means an individual end customer using the AXY Customer App and is a separate category of User from an Employee / Authorized User.</p>
<p class="legal-definition">1.6 “Listing” means any product, quotation, price, image, document, certification or business information posted, transmitted or displayed through the Application by a User, an AXY Business Customer, a participating manufacturer or AXY, as applicable.</p>
<p class="legal-definition">1.7 “Content” means all Listings, messages, images, files, text, data, product descriptions, communications and other materials transmitted, uploaded, shared or stored through the Application.</p>
<p class="legal-definition">1.8 “Services” means the functionalities and services made available through the Application, including the functionalities of the AXY Back Office, AXY Sales App and AXY Customer App, as enabled for the relevant User, AXY Business Customer or module.</p>
<p class="legal-definition">1.9 “Organization Account” means the top-level AXY account through which an AXY Business Customer manages its Business Units, Locations, Employees / Authorized Users and Modules.</p>
<p class="legal-definition">1.10 “Business Unit” means a configured operational and data-management area belonging to an Organization Account.</p>
<p class="legal-definition">1.11 “Location” means a physical or operational site assigned to a Business Unit.</p>
<p class="legal-definition">1.12 “Module” means an optional feature set ordered or enabled in addition to the Free Account or core Services.</p>
<p class="legal-definition">1.13 “Third-Party Service” means a service, system or infrastructure not operated by AXY, including communication providers and integrated external systems, which may be subject to its own availability, functionality, terms and policies.</p>
<p>AXY is a freemium B2B software platform for retail businesses, brands and their authorized employees. It connects product information, in-store sales activity, customers, stock visibility, follow-up, warranties, partner collaboration and business communication in one operating environment, with the purpose of enhancing the customer experience. Individual end customers may use the consumer-facing AXY Customer App.</p>
<p>Unless expressly stated for a particular functionality, AXY provides the technology platform and related Services and does not itself act as a buyer, seller, exporter, importer, distributor or trading company in transactions between participating businesses and their customers.</p>
<p>By accessing, registering on, or using the AXY Application, you acknowledge that you have read, understood, and agree to be legally bound by the following Terms and Conditions.</p>
<p>You must read, agree with and accept these Terms and acknowledge the Privacy Policy before signing up for an AXY Account. If you use the Application as or on behalf of an AXY Business Customer and AXY processes personal data on that business customer’s behalf, the applicable Data Processing Agreement (“DPA”) governs such processing and forms part of the contractual arrangements between AXY and that AXY Business Customer.</p>
<p>For the avoidance of doubt, these Terms govern the contractual use of the Application. The Privacy Policy governs AXY’s processing of personal data while the DPA governs processing carried out by AXY as processor on behalf of an AXY Business Customer. In the event of an inconsistency, the document specifically governing the relevant subject matter shall apply, subject always to applicable mandatory law.</p>
<h3 id="terms-consumer-rights">Consumer Rights</h3>
<p>If you are a Consumer, you may have certain rights under mandatory consumer protection laws applicable to you.</p>
<p>Nothing in these Terms is intended to exclude, restrict or modify any rights or remedies granted to Consumers under applicable mandatory law which cannot lawfully be excluded, restricted or modified by agreement. In the event of any conflict between these Terms and such mandatory provisions, the mandatory provisions shall prevail to the extent of such conflict.</p>
<h3 id="terms-registration-and-managing-the-account">Registration and Managing the Account</h3>
<p>By registering for using the AXY application, you represent and warrant that:</p>
<p>(a) you have the legal capacity to enter into these Terms;</p>
<p>(b) if acting on behalf of a company, you are duly authorized to bind that company; and</p>
<p>(c) all information you provide is true, accurate, current, and complete.</p>
<p>You are solely responsible for maintaining the confidentiality and security of your login credentials and for all activities conducted through your account.</p>
<p>To access and use those Services that require registration, you must register for an AXY account (“Account”). The information required for registration depends on the relevant Application and User category and may include name and surname, e-mail address, telephone number, business or organisation details, login/account identifiers and other information indicated as required. Personal data collected in connection with registration is processed as described in the Privacy Policy.</p>
<p>AXY may reject your application for an Account, or cancel an existing Account, for any reason, at our sole discretion, subject to applicable law and any mandatory rights applicable to Consumers.</p>
<p>Individual Customer App Accounts may be registered only by persons who are at least 18 years of age. The Customer App may be technically downloadable or accessible by persons under the age of 18 where permitted by the relevant app store, device or account settings; however, persons under 18 are not permitted to register or maintain an individual AXY Account. AXY does not knowingly permit persons under 18 to create an individual Customer App Account and may suspend or delete an Account if it reasonably determines that this age requirement has not been met, subject to applicable law.</p>
<p>You are responsible for keeping your password secure. AXY shall not be liable for any loss or damage from your failure to maintain the security of your Account and password.</p>
<p>If you are an AXY Business Customer, you are responsible for the administration of your organisation Account, the authorization and management of your Employees / Authorized Users, your materials, and the goods and services that you offer or manage through the Services.</p>
<p>If you are an AXY Business Customer, you are responsible for all aspects of transactions and the customer relationship between you and your customer(s), except to the extent that AXY expressly assumes responsibility for a particular Service.</p>
<p>You represent and warrant that you will comply with all applicable laws, rules, regulations and rights of third parties in your use of any of the Services and your performance of obligations under these Terms.</p>
`;
