export default `<h3 id="terms-user-content-and-conduct">User Content and Conduct</h3>
<p>The Application may be made available internationally. Users must comply with the laws and regulations applicable to their use of the Application and with these Terms.</p>
<p>We encourage all users to ensure that the content they post aligns with these legal requirements and our policies.</p>
<p>Users bear full responsibility for ensuring that the information they share is lawful and compliant with our policies and the applicable legal frameworks.</p>
<p>Users may not post, upload, transmit or otherwise make available through the Application any Content that is unlawful under applicable law or prohibited by these Terms.</p>
<p>AXY may review or monitor Listings and other Content where appropriate and reserves the right to remove or restrict access to Content that violates these Terms or applicable law, subject to applicable mandatory law. AXY does not generally review or proactively monitor all Listings or other Content made available through the Application and is under no general obligation to do so, except where required by applicable law.</p>
<h3 id="terms-intellectual-property-ip-rights-policy">Intellectual Property (IP) Rights Policy</h3>
<p>All rights in the AXY software, trademarks, logos and content created or owned by XY belong to XY or its licensors, as applicable. User Content remains subject to the rights of the relevant User or other rights holder.</p>
<p>Except as expressly permitted by these Terms or the intended functionality of the relevant Service, you agree not to reproduce, duplicate, copy, sell, resell, sublicense or otherwise exploit any portion of the Application, the Services or AXY-owned Content without the express written permission of XY.</p>
<p>AXY grants Users a limited, non-exclusive, non-transferable and revocable right to access and use the Application for the purposes and within the scope for which the relevant Application, Account and/or module is made available to them, including legitimate internal business use by AXY Business Customers and their Employees / Authorized Users. This right does not permit resale, sublicensing, unauthorized commercial exploitation, systematic extraction or reuse of Listings or other AXY-owned Content, creation of derivative services based on the Application, or any other use outside the intended functionality of the Services, unless expressly authorized by XY in writing. Any unauthorized use may result in suspension or termination of the relevant permission, Account or access, subject to applicable law.</p>
<h3 id="terms-third-party-ip">Third-party IP</h3>
<p>We respect intellectual property rights and require all users to comply with IPR laws and regulations. Posting counterfeit, replica, or unauthorized branded items is strictly prohibited.</p>
<p>If you encounter any product or content that appears to violate this policy or infringe IPR, please report it to us at the contact set below.</p>
<p>Users grant AXY a non-exclusive, worldwide, royalty-free licence to host, store, reproduce, display, transmit and otherwise process their Content solely to the extent reasonably necessary to operate, provide, secure and improve the Services and to perform AXY&#x27;s obligations under these Terms, subject to the Privacy Policy and, where applicable, the DPA.</p>
<p>Users remain responsible for the Content they submit or make available through the Application and represent and warrant that they have all rights, licences, permissions and other authorisations necessary for AXY and other authorised recipients to use such Content as contemplated by these Terms and the relevant functionality of the Services.</p>
<h3 id="terms-payments-and-third-party-payment-services">Payments and Third-Party Payment Services</h3>
<p>AXY does not itself provide payment processing services and does not collect, receive or store full payment card details where such information is submitted directly to Stripe or another third-party payment service provider.</p>
<p>Payments by AXY Business Customers may be processed through Stripe or another third-party payment service provider as made available in AXY&#x27;s web application or other B2B commercial process. Where Stripe is used, the payment transaction is processed by Stripe in accordance with Stripe&#x27;s applicable terms and conditions, privacy policy and payment method rules. Information necessary to process the payment may be provided directly to or processed by Stripe in accordance with its applicable terms and privacy policy.</p>
<p>No checkout or payment functionality is made available within AXY&#x27;s iOS applications. The iOS applications do not enable the purchase of paid digital functionalities and do not direct Users to an external payment method or external checkout. They provide access only to functionality that has otherwise been made available to the relevant User or AXY Business Customer in accordance with the applicable Account, subscription, order or commercial arrangement.</p>
<p>Paid Services are offered to AXY Business Customers only. Business subscriptions, additional users, additional Business Units, paid modules, AI packages and other paid business functionalities, where applicable, are ordered, contracted and paid exclusively through AXY&#x27;s web application or another B2B commercial process made available by AXY. The applicable fees, subscription terms and scope of the purchased Services may be specified in the relevant order form, pricing schedule, web-based ordering process or other commercial arrangement with the AXY Business Customer.</p>
<p>The AXY Customer App is provided free of charge to Customer App Users. Customer App Users do not purchase paid subscriptions, modules, packages or other paid digital functionalities through the Customer App.</p>
<h3 id="terms-order-forms-and-commercial-terms">Order Forms and Commercial Terms</h3>
<p>Certain paid Services, additional capacity, Modules, integrations or other commercial functionalities may be subject to a separate order form, subscription plan, pricing schedule or other commercial agreement agreed between AXY and the relevant AXY Business Customer (collectively, an “Order Form”).</p>
<p>The applicable Order Form may specify, among other matters, the Services or Modules purchased, licensed quantities, fees, subscription term, billing arrangements, support and integration scope and any applicable usage limits.</p>
<p>In the event of a conflict between these Terms and an Order Form in relation to the specific commercial Services covered by that Order Form, the Order Form shall prevail solely with respect to those specific commercial terms, unless expressly stated otherwise.</p>
<h3 id="terms-licensed-capacity-and-modules">Licensed Capacity and Modules</h3>
<p>AXY Business Customers may access such Business Units, Locations, Employee / Authorized User seats, Modules and other functionality as are included in their applicable Account, subscription or Order Form.</p>
<p>AXY may technically enforce applicable licensed quantities and enabled Modules and may restrict the creation or use of additional capacity or functionality until such additional capacity or functionality has been ordered or otherwise expressly enabled by AXY.</p>
<p>The AXY Business Customer is responsible for allocating and managing its licensed capacity, including Employee / Authorized User access, Business Units and Locations, in accordance with its applicable subscription and permissions.</p>
<h3 id="terms-third-party-services-and-integrations">Third-Party Services and Integrations</h3>
<p>Certain Services or Modules may connect to or depend upon Third-Party Services, systems or infrastructure, including communication providers, ERP, POS, CRM, e-commerce, inventory or other external systems.</p>
<p>The availability and operation of such functionality may depend on third-party approvals, APIs, systems, policies, service availability and data supplied by the AXY Business Customer or the relevant third party. Changes to or interruptions of Third-Party Services, API limitations, outages or inaccurate or delayed source data may therefore affect the availability, accuracy or operation of connected AXY functionality.</p>
<p>Unless expressly agreed otherwise, AXY does not provide or replace the underlying Third-Party Service and is not responsible for matters within the control of the relevant third-party provider. The AXY Business Customer is responsible for ensuring lawful access to third-party systems, maintaining valid credentials and permissions, and providing any cooperation reasonably required for the relevant integration.</p>
<p>Stock and synchronized information displayed through AXY may originate from information entered by an AXY Business Customer or from integrated external systems. Its accuracy, completeness and timeliness may therefore depend on the relevant source system, source data and synchronization schedule.</p>
`;
