export default `<h3 id="terms-privacy-and-data-protection">Privacy and Data Protection</h3>
<p>AXY is committed to protecting personal data processed in connection with the Application, including personal data of Customer App Users, Employees / Authorized Users and other data subjects.</p>
<p>Where AXY determines the purposes and means of processing personal data for its own purposes, including administration, security, analytics and development of the Application, AXY acts as data controller. Such processing is governed by the Privacy Policy, which describes, among other matters, the categories and purposes of processing, recipients, transfers, retention, deletion and data-subject rights.</p>
<p>Where an AXY Business Customer enters or otherwise makes personal data available through the Application and AXY processes that data solely on behalf of that business customer and in accordance with its instructions, the AXY Business Customer acts as data controller and AXY generally acts as data processor. The AXY Business Customer is responsible for ensuring that such personal data is processed lawfully and that data subjects receive the information required by applicable data protection law.</p>
<p>Processing carried out by AXY as processor on behalf of an AXY Business Customer is further governed by the applicable Data Processing Agreement (“DPA”). The respective controller and processor roles may therefore differ depending on the relevant Application, User category, enabled functionality and processing activity.</p>
<h3 id="terms-ai-generated-content-and-ai-assisted-services">AI-Generated Content and AI-Assisted Services</h3>
<p>Certain functionalities of the Application may use artificial intelligence systems to assist Users in generating, reviewing, summarising or otherwise processing Content. AI-generated output may be inaccurate, incomplete, outdated or otherwise inappropriate and should not be relied upon without appropriate review.</p>
<p>Users remain responsible for reviewing AI-generated output before using, publishing, communicating or otherwise relying on it and for ensuring that their use of such output complies with applicable law and does not infringe third-party rights. Users retain any rights they may have in Content submitted to AI-enabled functionalities. To the extent necessary to provide the relevant functionality, Users grant AXY the rights necessary to process such Content for the purpose of providing the Services. AXY does not guarantee that AI-generated output will be unique or that identical or similar output will not be generated for other users. To the extent permitted by applicable law, AXY does not warrant that AI-generated output is accurate, complete, suitable for a particular purpose or free from third-party rights. All provisions of these Terms apply regardless of whether Content is generated or processed using AI-enabled functionality.</p>
<h3 id="terms-term-and-termination">Term and Termination</h3>
<p>The term of these Terms will begin on the day you complete registration for use of a Service and continue until terminated by us or by you, as provided below.</p>
<p>A User may terminate use of the Services or an Account in accordance with the functionality available for the relevant User category. A Customer App User may initiate permanent deletion of the entire AXY Account and related personal data under AXY’s control by selecting “Delete account” in the Customer App, verifying identity using a password or one-time password (OTP), and submitting the deletion request. AXY will manually process the request within one business day and send confirmation by e-mail upon completion, subject to retention required or permitted for invoicing, accounting or other statutory obligations, warranty or contractual relationships, or the establishment, exercise or defence of legal claims. Other Account termination requests may be handled through the applicable account administration process or by contacting AXY.</p>
<p>We may terminate your account at any time. Without limiting any other remedies, we may suspend or terminate your Account or these Terms for any reason, without notice and at any time (unless otherwise required by law), including if we suspect that you (by conviction, settlement, insurance or escrow investigation, or otherwise) have engaged in fraudulent activity in connection with the use of the Services.</p>
<p>Where required by applicable law, including applicable consumer protection law, AXY will provide the User with reasonable prior notice of suspension or termination and, where required, the reasons for such suspension or termination.</p>
<p>Nothing in this section shall limit any rights or remedies available to consumers under applicable mandatory law.</p>
<p>Termination of the Terms will be without prejudice to any rights or obligations which arose prior to the date of termination.</p>
<h3 id="terms-amendments">Amendments</h3>
<p>XY may modify these Terms at any time and at its sole discretion.</p>
<p>Your rights under these Terms will be subject to the most current version of these Terms.</p>
<p>Continued use of the AXY constitutes acceptance of the updated Terms.</p>
<p>Where required by applicable law, Users will be informed in advance of material changes to these Terms. Any changes affecting consumers shall be subject to applicable mandatory consumer protection laws and shall not limit any rights or remedies available to consumers under such laws.</p>
<p>If you do not agree with these Terms of Use, do not use the Application.</p>
<h3 id="terms-severability">Severability</h3>
<p>If any provision, or portion of the provision, in these Terms is, for any reason, held to be invalid, illegal or unenforceable in any respect, then such invalidity, illegality or unenforceability will not affect any other provision (or the unaffected portion of the provision) of the Terms, and the Terms will be construed as if such invalid, illegal or unenforceable provision, or portion of the provision, had never been contained within the Terms.</p>
<h3 id="terms-governing-law-and-jurisdiction">Governing Law and Jurisdiction</h3>
<p>These Terms shall be governed by and construed in accordance with the laws of the Republic of Croatia.</p>
<p>All disputes arising out of or relating to these Terms, including those relating to their breach, termination or invalidity, and any legal consequences thereof, shall, where reasonably possible, be settled amicably.</p>
<p>In the absence of an amicable settlement, any dispute shall be subject to the jurisdiction of the competent Croatian courts, unless otherwise provided by applicable mandatory law.</p>
<p>If you are a Consumer, the choice of Croatian law shall not deprive you of the protection afforded to you by provisions that cannot be derogated from by agreement under the law that would otherwise be applicable to you. Nothing in this section shall affect any mandatory rights of consumers regarding applicable law or jurisdiction.</p>
<h3 id="terms-contact">Contact</h3>
<p>For any questions related to these Terms, please contact us at: <strong><a href="mailto:jure@axy.net">jure@axy.net</a></strong>.</p>`;
